### ISSUE TITLE
Error in supybot-wizard

### ISSUE THREAD

**Issue by nyuszika7h** [ProgVal/Limnoria#1020]
```
 What language do you want to use? (default: en)

Traceback (most recent call last):
  File "/home/nyuszika7h/tmp/nsxi2/venv/bin/supybot-wizard", line 721, in <module>
    main()
  File "/home/nyuszika7h/tmp/nsxi2/venv/bin/supybot-wizard", line 252, in main
    import supybot.plugin as plugin
  File "/home/nyuszika7h/tmp/nsxi2/venv/local/lib/python2.7/site-packages/supybot/plugin.py", line 37, in <module>
    from . import callbacks, conf, log, registry
  File "/home/nyuszika7h/tmp/nsxi2/venv/local/lib/python2.7/site-packages/supybot/callbacks.py", line 54, in <module>
    from . import (conf, ircdb, irclib, ircmsgs, ircutils, log, registry, utils,
  File "/home/nyuszika7h/tmp/nsxi2/venv/local/lib/python2.7/site-packages/supybot/irclib.py", line 1015
    except (BadDigestError, OSError, ValueError) as e:
         ^
SyntaxError: invalid syntax
```

**Comment by nyuszika7h** [comment]
Never mind, I caused this error with a local change.

**Comment by ProgVal** [comment]
:+1:
