### ISSUE TITLE
Failing to connect to freenode

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1028]
The latest lines from messages.log:

```
TypeError: expected bytes, not str
ERROR 2015-01-24T18:14:29 supybot Exception id: 0x7e15a
WARNING 2015-01-24T18:15:02 supybot Error message from freenode: Closing Link: vep.mikaela.info (Connection timed out)
INFO 2015-01-24T18:15:02 supybot Reconnecting to freenode.
INFO 2015-01-24T18:15:02 supybot Connecting to chat.freenode.net:7000.
INFO 2015-01-24T18:15:03 supybot freenode: Server acknowledged capability 'account-notify'
INFO 2015-01-24T18:15:04 supybot freenode: Server acknowledged capability 'extended-join'
INFO 2015-01-24T18:15:05 supybot freenode: Server acknowledged capability 'multi-prefix'
INFO 2015-01-24T18:15:06 supybot freenode: Server acknowledged capability 'sasl'
INFO 2015-01-24T18:15:08 supybot freenode: Authenticating using SASL.
ERROR 2015-01-24T18:15:10 supybot Uncaught exception in Irc.feedMsg:
Traceback (most recent call last):
  File "/home/users/mikaela/.local/lib/python3.2/site-packages/supybot/log.py", line 361, in m
    return f(self, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.2/site-packages/supybot/irclib.py", line 854, in feedMsg
    method(msg)
  File "/home/users/mikaela/.local/lib/python3.2/site-packages/supybot/irclib.py", line 1009, in doAuthenticate
    private_key.sign(base64.b64decode(msg.args[0]))).decode('utf-8')
  File "/usr/lib/python3.2/base64.py", line 83, in b64decode
    raise TypeError("expected bytes, not %s" % s.__class__.__name__)
TypeError: expected bytes, not str
ERROR 2015-01-24T18:15:10 supybot Exception id: 0x7e15a
WARNING 2015-01-24T18:15:42 supybot Error message from freenode: Closing Link: vep.mikaela.info (Connection timed out)
INFO 2015-01-24T18:15:42 supybot Reconnecting to freenode.
INFO 2015-01-24T18:15:42 supybot Connecting to chat.freenode.net:7000.
INFO 2015-01-24T18:15:44 supybot freenode: Server acknowledged capability 'account-notify'
INFO 2015-01-24T18:15:46 supybot freenode: Server acknowledged capability 'extended-join'
INFO 2015-01-24T18:15:47 supybot freenode: Server acknowledged capability 'multi-prefix'
INFO 2015-01-24T18:15:48 supybot freenode: Server acknowledged capability 'sasl'
INFO 2015-01-24T18:15:51 supybot freenode: Authenticating using SASL.
ERROR 2015-01-24T18:15:51 supybot Uncaught exception in Irc.feedMsg:
Traceback (most recent call last):
  File "/home/users/mikaela/.local/lib/python3.2/site-packages/supybot/log.py", line 361, in m
    return f(self, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.2/site-packages/supybot/irclib.py", line 854, in feedMsg
    method(msg)
  File "/home/users/mikaela/.local/lib/python3.2/site-packages/supybot/irclib.py", line 1009, in doAuthenticate
    private_key.sign(base64.b64decode(msg.args[0]))).decode('utf-8')
  File "/usr/lib/python3.2/base64.py", line 83, in b64decode
    raise TypeError("expected bytes, not %s" % s.__class__.__name__)
TypeError: expected bytes, not str
ERROR 2015-01-24T18:15:51 supybot Exception id: 0x7e15a
```

```
Supybot 0.83.4.1+limnoria 2015.01.23 running on Python3.2.3 (default, Feb 20 2013, 14:44:27) 
[GCC 4.7.2]
```

**Comment by Mikaela** [comment]
I also asked this on \#limnoria without ever getting response.

**Comment by GLolol** [comment]
Looks like a bug with SASL ECSDA: `File "/home/users/mikaela/.local/lib/python3.2/site-packages/supybot/irclib.py", line 1009, in doAuthenticate
    private_key.sign(base64.b64decode(msg.args[0]))).decode('utf-8')`

**Comment by GLolol** [comment]
Try this patch:

```patch
diff --git a/src/irclib.py b/src/irclib.py
index 7252689..0f8d0b2 100644
--- a/src/irclib.py
+++ b/src/irclib.py
@@ -1009,7 +1009,7 @@ class Irc(IrcCommandDispatcher):
                 private_key = SigningKey.from_pem(open(self.sasl_ecdsa_key).
                     read())
                 authstring = base64.b64encode(
-                    private_key.sign(base64.b64decode(msg.args[0]))).decode('utf-8')
+                    private_key.sign(base64.b64decode(msg.args[0].encode()))).decode('utf-8')
             except (BadDigestError, OSError, ValueError) as e:
                 authstring = "*"
```

**Comment by Mikaela** [comment]
That works.

**Comment by Mikaela** [comment]
But SASL ECDSA-256CHALLENGEAUTH fails, but on Python 2 bot that doesn't have this issue, it's not even attempted.

**Comment by GLolol** [comment]
Someone else should take a look at this, I'm not quite familiar with it.

**Comment by Mikaela** [comment]
I think maybe you should open pull request with that patch as getting connected is probably bigger issue.
