### ISSUE TITLE
Multiple plugins have unicode handling issues only exposed when tests run without --no-network

### ISSUE THREAD

**Issue by NP-Hardass** [ProgVal/Limnoria#1096]
First reported here: https://bugs.gentoo.org/show_bug.cgi?id=547058
Multiple plugins have unicode issues that were only exposed when running supybot-test without the --no-network flag.
We are using charade, and not chardet, as per requirements.txt

```
testNonSnarfing (Web.test.WebTestCase) ... /usr/lib64/python2.7/site-packages/charade/universaldetector.py:74: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aBuf[:3] == codecs.BOM:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:77: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:80: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:83: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\xFE\xFF\x00\x00':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:89: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\x00\x00\xFF\xFE':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:95: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:98: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_BE:
ok
testNonSnarfingRegexpConfigurable (Web.test.WebTestCase) ... ok
testSize (Web.test.WebTestCase) ... ok
testTitle (Web.test.WebTestCase) ... /usr/lib64/python2.7/site-packages/charade/universaldetector.py:74: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aBuf[:3] == codecs.BOM:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:77: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:80: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:83: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\xFE\xFF\x00\x00':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:89: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\x00\x00\xFF\xFE':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:95: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:98: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:74: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aBuf[:3] == codecs.BOM:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:77: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:80: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:83: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\xFE\xFF\x00\x00':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:89: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\x00\x00\xFF\xFE':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:95: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:98: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:74: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aBuf[:3] == codecs.BOM:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:77: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:80: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:83: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\xFE\xFF\x00\x00':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:89: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\x00\x00\xFF\xFE':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:95: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:98: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:74: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aBuf[:3] == codecs.BOM:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:77: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:80: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:83: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\xFE\xFF\x00\x00':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:89: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\x00\x00\xFF\xFE':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:95: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:98: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:74: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aBuf[:3] == codecs.BOM:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:77: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:80: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:83: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\xFE\xFF\x00\x00':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:89: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\x00\x00\xFF\xFE':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:95: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:98: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_BE:
ok
testTitleSnarfer (Web.test.WebTestCase) ... /usr/lib64/python2.7/site-packages/charade/universaldetector.py:74: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aBuf[:3] == codecs.BOM:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:77: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:80: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:83: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\xFE\xFF\x00\x00':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:89: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\x00\x00\xFF\xFE':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:95: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:98: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_BE:
Exception in thread Thread #15 (for snarfing http://microsoft.com/):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/site-packages/supybot/commands.py", line 163, in run
    super(UrlSnarfThread, self).run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/supybot/commands.py", line 214, in doSnarf
    f(self, irc, msg, match, *L, **kwargs)
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/Web/plugin.py", line 100, in newf
    pn=self.name(), cn=f.__name__)
  File "/usr/lib64/python2.7/site-packages/supybot/commands.py", line 131, in process
    raise v
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 10: ordinal not in range(128)

FAIL
testAliasImport (Aka.test.AkaTestCase) ... /usr/lib64/python2.7/site-packages/supybot/callbacks.py:1181: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if name != canonicalName(name):
ok
testGoosnarf (ShrinkUrl.test.ShrinkUrlTestCase) ... FAIL
testNonSnarfing (ShrinkUrl.test.ShrinkUrlTestCase) ... ok
testShrink (ShrinkUrl.test.ShrinkUrlTestCase) ... FAIL
testShrinkCycle (ShrinkUrl.test.ShrinkUrlTestCase) ... FAIL
testTinysnarf (ShrinkUrl.test.ShrinkUrlTestCase) ... ok
testUr1snarf (ShrinkUrl.test.ShrinkUrlTestCase) ... FAIL
testX0snarf (ShrinkUrl.test.ShrinkUrlTestCase) ... FAIL
testCalc (Google.test.GoogleTestCase) ... /usr/lib64/python2.7/site-packages/charade/universaldetector.py:74: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if aBuf[:3] == codecs.BOM:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:77: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:80: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == codecs.BOM_UTF32_BE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:83: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\xFE\xFF\x00\x00':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:89: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:4] == b'\x00\x00\xFF\xFE':
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:95: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_LE:
/usr/lib64/python2.7/site-packages/charade/universaldetector.py:98: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif aBuf[:2] == codecs.BOM_BE:
ok

======================================================================
FAIL: testTitleSnarfer (Web.test.WebTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 154, in runTest
    originalRunTest()
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/Web/test.py", line 76, in testTitleSnarfer
    'Microsoft')
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 343, in assertSnarfRegexp
    usePrefixChar=False, **kwargs)
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 336, in assertRegexp
    raise TimeoutError(query)
TimeoutError: 'http://microsoft.com/' timed out

======================================================================
FAIL: testGoosnarf (ShrinkUrl.test.ShrinkUrlTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 154, in runTest
    originalRunTest()
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/ShrinkUrl/test.py", line 93, in testGoosnarf
    self._snarf('goo')
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/ShrinkUrl/test.py", line 84, in _snarf
    self.assertSnarfRegexp(url, teststr)
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 343, in assertSnarfRegexp
    usePrefixChar=False, **kwargs)
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 336, in assertRegexp
    raise TimeoutError(query)
TimeoutError: 'http://sourceforge.net/p/supybot/bugs/?source=navbar' timed out

======================================================================
FAIL: testShrink (ShrinkUrl.test.ShrinkUrlTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 154, in runTest
    originalRunTest()
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/ShrinkUrl/test.py", line 54, in testShrink
    shrunkurl)
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 338, in assertRegexp
    '%r does not match %r' % (m.args[1], regexp))
AssertionError: 'Error: HTTP Error 403: Forbidden' does not match 'http://goo.gl/3c59N'

======================================================================
FAIL: testShrinkCycle (ShrinkUrl.test.ShrinkUrlTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 154, in runTest
    originalRunTest()
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/ShrinkUrl/test.py", line 68, in testShrinkCycle
    self.tests['goo'][1][1])
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 343, in assertSnarfRegexp
    usePrefixChar=False, **kwargs)
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 336, in assertRegexp
    raise TimeoutError(query)
TimeoutError: 'http://www.urbandictionary.com/define.php?term=all+your+base+are+belong+to+us' timed out

======================================================================
FAIL: testUr1snarf (ShrinkUrl.test.ShrinkUrlTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 154, in runTest
    originalRunTest()
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/ShrinkUrl/test.py", line 96, in testUr1snarf
    self._snarf('ur1')
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/ShrinkUrl/test.py", line 84, in _snarf
    self.assertSnarfRegexp(url, teststr)
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 343, in assertSnarfRegexp
    usePrefixChar=False, **kwargs)
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 338, in assertRegexp
    '%r does not match %r' % (m.args[1], regexp))
AssertionError: '<\x02http://ur1.ca/ceqh8\x02> (at sourceforge.net)' does not match '.*http://ur1.ca/9xl25.* \\(at'

======================================================================
FAIL: testX0snarf (ShrinkUrl.test.ShrinkUrlTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 154, in runTest
    originalRunTest()
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/ShrinkUrl/test.py", line 99, in testX0snarf
    self._snarf('x0')
  File "/usr/lib64/python2.7/site-packages/supybot/plugins/ShrinkUrl/test.py", line 84, in _snarf
    self.assertSnarfRegexp(url, teststr)
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 343, in assertSnarfRegexp
    usePrefixChar=False, **kwargs)
  File "/usr/lib64/python2.7/site-packages/supybot/test.py", line 338, in assertRegexp
    '%r does not match %r' % (m.args[1], regexp))
AssertionError: '<\x02http://x0.no/a53s\x02> (at sourceforge.net)' does not match '.*http://x0.no/0l2j.* \\(at'

======================================================================
```

**Comment by ProgVal** [comment]
ShrinkUrl tests should be fixed in testing.

And if I understood correctly, the failing Web test can be fixed by using chardet.
Should I update requirements.txt?

**Comment by NP-Hardass** [comment]
With chardet, and no charade, on the testing branch, the only one that remains is

```
testAliasImport (Aka.test.AkaTestCase) ... /var/tmp/portage/net-irc/limnoria-99999999/work/limnoria-99999999-python2_7/build/lib/supybot/callbacks.py:1181: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if name != canonicalName(name):
ok
````

**Comment by ProgVal** [comment]
So everything is fine

**Comment by NP-Hardass** [comment]
Yeah, so I guess update requirements.txt and I'd say close it up.

I assume that you are tackling the Aka plugin unicode issue elsewhere?

**Comment by ProgVal** [comment]
By recommending people to use Python 3?

**Comment by NP-Hardass** [comment]
Haha.
