### ISSUE TITLE
'whois' command is broken in latest testing branch

### ISSUE THREAD

**Issue by GLolol** [ProgVal/Limnoria#1105]
After the latest Supybot-master merge, the `whois` command is completely broken.

https://github.com/ProgVal/Limnoria/blob/testing/src/ircutils.py#L398 seems to be the culprit: `self._whois` is not defined in `ircutils.formatWhois()`, but in the Network plugin.

```
Traceback (most recent call last):
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/log.py", line 361, in m
    return f(self, *args, **kwargs)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/irclib.py", line 131, in __call__
    method(irc, msg)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/plugins/Network/plugin.py", line 191, in do318
    command=command)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/ircutils.py", line 398, in formatWhois
    (replyIrc, replyMsg, d, command) = self._whois[(irc, loweredNick)]
NameError: name 'self' is not defined
```

**Comment by ProgVal** [comment]
82b8bf8
