### ISSUE TITLE
RSS with Python 3 breaks by Elisa's issue feed

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1116]
1. `rss add elisahairio http://esco.elisa.fi/rest/esco/bulletin/rss?tags=corporate.elisa.fi:disturbance`
2. `rss announce add elisahairio`
3. Restart the bot and it fails to load RSS and manual loading results to `Error: AssertionError: elisahairio`

*It should actually be elisahäiriö as I thought that the älphäbets are the cause of this issue, but apparently not.*

```pytb
INFO 2015-05-20T23:39:24 supybot load called on ##Mikaela by "Mikaela!mikaela@unaffiliated/mikaela".
ERROR 2015-05-20T23:39:24 supybot Uncaught exception in ['load'].
Traceback (most recent call last):
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/callbacks.py", line 1279, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/callbacks.py", line 1260, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/commands.py", line 1079, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/Owner/plugin.py", line 443, in load
    cb = plugin.loadPluginClass(irc, module)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugin.py", line 109, in loadPluginClass
    cb = module.Class(irc)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/utils/python.py", line 103, in __init__
    original__init__(self, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/RSS/plugin.py", line 170, in __init__
    self.register_feed(name, url, True, True, announced.get(name, []))
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/RSS/plugin.py", line 216, in register_feed
    plugin_is_loading, announced)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/RSS/plugin.py", line 86, in __init__
    assert utils.web.httpUrlRe.match(name), name
AssertionError: elisahairio
ERROR 2015-05-20T23:39:24 supybot Exception id: 0x9e3e0
```

* `The current (running) version of this Supybot is 0.83.4.1+limnoria 2015.05.20, running on Python 3.4.3 (default, May  9 2015, 06:38:10)  [GCC 4.7.2].  The newest versions available online are 2015.05.20 (in master), 2015.05.20 (in testing).`

**Comment by Mikaela** [comment]
How is this invalid feed name?

**Comment by ProgVal** [comment]
s/name/URL/

**Comment by Mikaela** [comment]
How is the feed URL invalid then?

**Comment by ProgVal** [comment]
“elisahairio” is not a valid URL

**Comment by Mikaela** [comment]
I still don't understand.

First you add the RSS feed with `rss add feedname url` and if you wish it to be automatically announced on the channel, you use `rss announce add feedname`.

**Comment by ProgVal** [comment]
I fixed the crash you reported, which was about starting with an invalid config.

If you still have an error, that's another issue

**Comment by Mikaela** [comment]
I don't understand how the config was invalid and I don't understand the config message either.

I don't have errors since the latest version. Why are you releasing so many Limnorias lately, by the way?

**Comment by ProgVal** [comment]
> I don't understand how the config was invalid and I don't understand the config message either.

I don't know either. As I said, that's a different bug.

> Why are you releasing so many Limnorias lately, by the way?

Because I changed the build system, and I also had to make a bugfix release
