### ISSUE TITLE
Google Translate tracebacks

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1144]
```
2015-07-27 14:49:35+0300 <@Mikaela> +google translate ch en 由于目前系统繁忙，系统暂时无法访问，请稍后访问查询！ 
2015-07-27 14:49:37+0300 <@Euforia> Error: TypeError: 'NoneType' object is not iterable
```

```pytb
INFO 2015-07-27T14:49:35 supybot google translate called on ##Mikaela by "Mikaela!mikaela@unaffiliated/mikaela".
ERROR 2015-07-27T14:49:36 supybot Spec: [<context for something>, <context for to>, <context for something>, <context for text>]
ERROR 2015-07-27T14:49:36 supybot Received args: []
ERROR 2015-07-27T14:49:36 supybot Extra args: ['sourceLang', 'targetLang', 'text']
ERROR 2015-07-27T14:49:36 supybot Uncaught exception in ['google', 'translate'].
Traceback (most recent call last):
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/callbacks.py", line 1279, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/callbacks.py", line 1260, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/commands.py", line 1079, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/Google/plugin.py", line 278, in translate
    irc.reply(''.join(x[0] for x in data[0]), language)
TypeError: 'NoneType' object is not iterable
ERROR 2015-07-27T14:49:36 supybot Exception id: 0x61e40
INFO 2015-07-27T14:49:40 supybot defaultplugin called on ##Mikaela by "Mikaela!mikaela@unaffiliated/mikaela".
```

> The current (running) version of this Supybot is 0.83.4.1+limnoria 2015.07.08, running on Python 3.4.3 (default, Jul 26 2015, 21:48:41)  [GCC 4.2.1 Compatible Debian Clang 3.0 (tags/RELEASE_30/final)].  The newest versions available online are 2015.07.08 (in master), 2015.07.08 (in testing).

**Comment by GLolol** [comment]
This should be closed by #1171, which is merged in master now.
