### ISSUE TITLE
Error with IgnoreNonVoice

### ISSUE THREAD

**Issue by nyuszika7h** [ProgVal/Limnoria#1150]
```
ERROR 2015-08-13T17:05:34 Uncaught exception in IgnoreNonVoice.invalidCommand.
Traceback (most recent call last):
  File "/home/nyuszika7h/bots/caroline/venv/lib/python3.4/site-packages/supybot/callbacks.py", line 719, in callInvalidCommands
    cb.invalidCommand(self, self.msg, self.args)
  File "/home/nyuszika7h/bots/caroline/venv/lib/python3.4/site-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/home/nyuszika7h/bots/caroline/plugins/IgnoreNonVoice/plugin.py", line 70, in invalidCommand
    if not self._is_not_ignored(irc, msg):
  File "/home/nyuszika7h/bots/caroline/plugins/IgnoreNonVoice/plugin.py", line 59, in _is_not_ignored
    channel not in irc.state.channels:
AttributeError: 'NoneType' object has no attribute 'channels'
ERROR 2015-08-13T17:05:34 Exception id: 0xd38f9
INFO 2015-08-13T17:05:34 Not replying to + in ##ircah, not a command.
```

**Comment by ProgVal** [comment]
Can you provide the debug logs?

**Comment by nyuszika7h** [comment]
```
DEBUG 2015-08-15T15:43:30 Incoming message (freenode): :nyuszika7h!nyuszika7h@cadoth.net PRIVMSG ##aelita :++
DEBUG 2015-08-15T15:43:30 findCallbacksForArgs: []
DEBUG 2015-08-15T15:43:30 Calling invalidCommands.
DEBUG 2015-08-15T15:43:30 Spawning thread "Thread #1847 (for invalidCommands)".
DEBUG 2015-08-15T15:43:30 Calling IgnoreNonVoice.invalidCommand.
ERROR 2015-08-15T15:43:30 Uncaught exception in IgnoreNonVoice.invalidCommand.
Traceback (most recent call last):
  File "/home/nyuszika7h/bots/caroline/venv/lib/python3.4/site-packages/supybot/callbacks.py", line 719, in callInvalidCommands
    cb.invalidCommand(self, self.msg, self.args)
  File "/home/nyuszika7h/bots/caroline/venv/lib/python3.4/site-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/home/nyuszika7h/bots/caroline/plugins/IgnoreNonVoice/plugin.py", line 70, in invalidCommand
    if not self._is_not_ignored(irc, msg):
  File "/home/nyuszika7h/bots/caroline/plugins/IgnoreNonVoice/plugin.py", line 59, in _is_not_ignored
    channel not in irc.state.channels:
AttributeError: 'NoneType' object has no attribute 'channels'
ERROR 2015-08-15T15:43:30 Exception id: 0xd38f9
DEBUG 2015-08-15T15:43:30 Supybot version: 0.83.4.1+limnoria 2015.06.13

Locals by frame, innermost last:


Frame callInvalidCommands in /home/nyuszika7h/bots/caroline/venv/lib/python3.4/site-packages/supybot/callbacks.py at line 724
                   self.args = ['+']
                 self.action = None
                         cbs = [<IgnoreNonVoice IgnoreNonVoice <IgnoreNonVoice.plugin.IgnoreNonVoice object at 0x77255e310860>>, <ShrinkUrl ShrinkUrl <ShrinkUrl.plugin.ShrinkUrl object at 0x77255d43c470>>, <Ctcp Ctcp <Ctcp.plugi
n.Ctcp object at 0x77255f8c46a0>>, <Google Google <Google.plugin.Google object at 0x77255e354710>>, <Web Web <Web.plugin.Web object at 0x77255d43c978>>, <Misc Misc <Misc.plugin.Misc object at 0x77255e2760f0>>]
                          cb = <IgnoreNonVoice IgnoreNonVoice <IgnoreNonVoice.plugin.IgnoreNonVoice object at 0x77255e310860>>
                    self.msg = IrcMsg(prefix="nyuszika7h!nyuszika7h@cadoth.net", command="PRIVMSG", args=('##aelita', '++'))
              self.repliedTo = False
            self.finalEvaled = True
                 self.notice = None
                           e = AttributeError("'NoneType' object has no attribute 'channels'",)
                     self.to = None
                        self = <supybot.callbacks.NestedCommandsIrcProxy object at 0x772556c7da58>
                self.counter = 1
             self.prefixNick = False
                    self.irc = <supybot.callbacks.ReplyIrcProxy object at 0x772556c7dbe0>
                 self.nested = 0
                self.private = None
          self.noLengthCheck = None


Frame g in /home/nyuszika7h/bots/caroline/venv/lib/python3.4/site-packages/supybot/utils/python.py at line 93
        self._Synchronized_rlock = <_thread.RLock owner=0 count=0>
            self.classModule = <module 'IgnoreNonVoice' from '/home/nyuszika7h/bots/caroline/plugins/IgnoreNonVoice/__init__.py'>
                      kwargs = {}
                    self.cbs = []
                           f = <function IgnoreNonVoice.invalidCommand at 0x77255e263ea0>
        self._PluginMixin__parent = <super: <class 'PluginMixin'>, <IgnoreNonVoice object>>
                        lock = <_thread.RLock owner=0 count=0>
                        self = <IgnoreNonVoice IgnoreNonVoice <IgnoreNonVoice.plugin.IgnoreNonVoice object at 0x77255e310860>>
                        args = (<supybot.callbacks.NestedCommandsIrcProxy object at 0x772556c7da58>, IrcMsg(prefix="nyuszika7h!nyuszika7h@cadoth.net", command="PRIVMSG", args=('##aelita', '++')), ['+'])
                    self.log = <supybot.log.Logger object at 0x77255ff79390>


Frame invalidCommand in /home/nyuszika7h/bots/caroline/plugins/IgnoreNonVoice/plugin.py at line 70
        self._Synchronized_rlock = <_thread.RLock owner=0 count=0>
            self.classModule = <module 'IgnoreNonVoice' from '/home/nyuszika7h/bots/caroline/plugins/IgnoreNonVoice/__init__.py'>
                        self = <IgnoreNonVoice IgnoreNonVoice <IgnoreNonVoice.plugin.IgnoreNonVoice object at 0x77255e310860>>
                         irc = <supybot.callbacks.NestedCommandsIrcProxy object at 0x772556c7da58>
        self._PluginMixin__parent = <super: <class 'PluginMixin'>, <IgnoreNonVoice object>>
                         msg = IrcMsg(prefix="nyuszika7h!nyuszika7h@cadoth.net", command="PRIVMSG", args=('##aelita', '++'))
                      tokens = ['+']
                    self.cbs = []
                    self.log = <supybot.log.Logger object at 0x77255ff79390>


Frame _is_not_ignored in /home/nyuszika7h/bots/caroline/plugins/IgnoreNonVoice/plugin.py at line 59
        self._Synchronized_rlock = <_thread.RLock owner=0 count=0>
            self.classModule = <module 'IgnoreNonVoice' from '/home/nyuszika7h/bots/caroline/plugins/IgnoreNonVoice/__init__.py'>
                        self = <IgnoreNonVoice IgnoreNonVoice <IgnoreNonVoice.plugin.IgnoreNonVoice object at 0x77255e310860>>
                     channel = '+'
                         irc = IrcMsg(prefix="nyuszika7h!nyuszika7h@cadoth.net", command="PRIVMSG", args=('##aelita', '++'))
        self._PluginMixin__parent = <super: <class 'PluginMixin'>, <IgnoreNonVoice object>>
                         msg = <supybot.callbacks.NestedCommandsIrcProxy object at 0x772556c7da58>
                    self.cbs = []
                    self.log = <supybot.log.Logger object at 0x77255ff79390>

+-----------------------+
| End of locals display |
+-----------------------+


DEBUG 2015-08-15T15:43:30 Finished calling IgnoreNonVoice.invalidCommand.
DEBUG 2015-08-15T15:43:30 Calling ShrinkUrl.invalidCommand.
DEBUG 2015-08-15T15:43:30 Finished calling ShrinkUrl.invalidCommand.
DEBUG 2015-08-15T15:43:30 Calling Ctcp.invalidCommand.
DEBUG 2015-08-15T15:43:30 Finished calling Ctcp.invalidCommand.
DEBUG 2015-08-15T15:43:30 Calling Google.invalidCommand.
DEBUG 2015-08-15T15:43:30 Finished calling Google.invalidCommand.
DEBUG 2015-08-15T15:43:30 Calling Web.invalidCommand.
DEBUG 2015-08-15T15:43:30 Finished calling Web.invalidCommand.
DEBUG 2015-08-15T15:43:30 Calling Misc.invalidCommand.
DEBUG 2015-08-15T15:43:30 Misc.invalidCommand called (tokens ['+'])
DEBUG 2015-08-15T15:43:30 Finished calling Misc.invalidCommand.
DEBUG 2015-08-15T15:43:30 Done calling invalidCommands: Misc.
DEBUG 2015-08-15T15:43:31 Outgoing message (freenode): PRIVMSG ##aelita :Error: "+" is not a valid command.
```
