### ISSUE TITLE
KeyError in urllib when using ~google translate with interpolation

### ISSUE THREAD

**Issue by The-Compiler** [ProgVal/Limnoria#1204]
I'm running the latest git version, with `~x` aliased to `~google translate`, and using `{}` for interpolation.

This works:

```
<&The-Compiler> ~x en ja Hello
<foobar> The-Compiler: こんにちは
<&The-Compiler> ~x ja en こんにちは
<foobar> The-Compiler: good afternoon
```

but this doesn't:

```
<&The-Compiler> ~x ja en {x en ja Hello}
<foobar> The-Compiler: Error: KeyError: u'\u3053'
```

In the log:

```
ERROR 2016-01-05T17:21:55 Uncaught exception in ['google', 'translate'].
Traceback (most recent call last):
  File ".../supybot/callbacks.py", line 1271, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File ".../supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File ".../supybot/callbacks.py", line 1248, in callCommand
    method(irc, msg, *args, **kwargs)
  File ".../supybot/commands.py", line 1080, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File ".../supybot/plugins/Google/plugin.py", line 283, in translate
    (text, language) = self._translate(sourceLang, targetLang, text)
  File ".../supybot/plugins/Google/plugin.py", line 252, in _translate
    text = utils.web.urlquote(text)
  File "/usr/lib/python2.7/urllib.py", line 1303, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u3053'
```

**Comment by ProgVal** [comment]
This is a bug in Python. And it only happens with Python 2, so it will not be fixed.

I suggest that you upgrade to Python 3.

**Comment by The-Compiler** [comment]
Oh - I thought limnoria was Python 2 only, seems like things changed in all the years I used it (or supybot) :wink:

**Comment by ProgVal** [comment]
Actually, Limnoria works better with 3 than 2 now :)

**Comment by ProgVal** [comment]
(closed because limnoria no longer supports py2)
