### ISSUE TITLE
GitHub: git.io IndexError on gollum (wiki) URLs

### ISSUE THREAD

**Issue by nyuszika7h** [ProgVal/Limnoria#1207]
```py3tb
INFO 2016-01-13T12:07:27 HTTP request: 148.251.87.217 - "POST /github/ HTTP/1.0" 200 -
ERROR 2016-01-13T12:07:28 Cannot connect to git.io: list index out of range (https://github.com/lykoss/lykos.git)
ERROR 2016-01-13T12:07:28 Uncaught exception in GithubCallback.doPost:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/supybot/log.py", line 362, in m
    return f(self, *args, **kwargs)
  File "/home/nyuszika7h/bots/caroline/plugins/GitHub/plugin.py", line 154, in doPost
    self.plugin.announce.onPayload(headers, json.loads(form['payload'].value))
  File "/home/nyuszika7h/bots/caroline/plugins/GitHub/plugin.py", line 346, in onPayload
    'gollum', None)
  File "/home/nyuszika7h/bots/caroline/plugins/GitHub/plugin.py", line 233, in _createPrivmsg
    url = self._shorten_url(value)
  File "/home/nyuszika7h/bots/caroline/plugins/GitHub/plugin.py", line 207, in _shorten_url
    f.headers._headers))[0][1].strip()
IndexError: list index out of range
ERROR 2016-01-13T12:07:28 Exception id: 0xf3301
DEBUG 2016-01-13T12:07:28 Limnoria version: 0.83.4.1+limnoria 2016.01.05

Locals by frame, innermost last:


Frame m in /usr/local/lib/python3.4/site-packages/supybot/log.py at line 366
                        self = <GitHub.plugin.GithubCallback object at 0x7f8b84e25be0>
                      kwargs = {'form': FieldStorage(None, None, [MiniFieldStorage('payload', '{"pages":[{"page_name":"Home","title":"Home","summary":null,"action":"edited","sha":"40c2918e8594774bb1da2e5b84865a6fe89b3ad8","html_url":"https://github.com/lykoss/lykos/wiki/Home"}],"repository":{"id":16919993,"name":"lykos","full_name":"lykoss/lykos","owner":{"login":"lykoss","id":6707035,"avatar_url":"https://avatars.githubusercontent.com/u/6707035?v=3","gravatar_id":"","url":"https://api.github.com/users/lykoss","html_url":"https://github.com/lykoss","followers_url":"https://api.github.com/users/lykoss/followers","following_url":"https://api.github.com/users/lykoss/following{/other_user}","gists_url":"https://api.github.com/users/lykoss/gists{/gist_id}","starred_url":"https://api.github.com/users/lykoss/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lykoss/subscriptions","organizations_url":"https://api.github.com/users/lykoss/orgs","repos_url":"https://api.github.com/users/lykoss/repos","events_url":"https://api.github.com/users/lykoss/events{/privacy}","received_events_url":"https://api.github.com/users/lykoss/received_events","type":"Organization","site_admin":false},"private":false,"html_url":"https://github.com/lykoss/lykos","description":"Werewolf, the popular detective/social party game (a theme of Mafia)","fork":false,"url":"https://api.github.com/repos/lykoss/lykos","forks_url":"https://api.github.com/repos/lykoss/lykos/forks","keys_url":"https://api.github.com/repos/lykoss/lykos/keys{/key_id}","collaborators_url":"https://api.github.com/repos/lykoss/lykos/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/lykoss/lykos/teams","hooks_url":"https://api.github.com/repos/lykoss/lykos/hooks","issue_events_url":"https://api.github.com/repos/lykoss/lykos/issues/events{/number}","events_url":"https://api.github.com/repos/lykoss/lykos/events","assignees_url":"https://api.github.com/repos/lykoss/lykos/assignees{/user}","branches_url":"https://api.github.com/repos/lykoss/lykos/branches{/branch}","tags_url":"https://api.github.com/repos/lykoss/lykos/tags","blobs_url":"https://api.github.com/repos/lykoss/lykos/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/lykoss/lykos/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/lykoss/lykos/git/refs{/sha}","trees_url":"https://api.github.com/repos/lykoss/lykos/git/trees{/sha}","statuses_url":"https://api.github.com/repos/lykoss/lykos/statuses/{sha}","languages_url":"https://api.github.com/repos/lykoss/lykos/languages","stargazers_url":"https://api.github.com/repos/lykoss/lykos/stargazers","contributors_url":"https://api.github.com/repos/lykoss/lykos/contributors","subscribers_url":"https://api.github.com/repos/lykoss/lykos/subscribers","subscription_url":"https://api.github.com/repos/lykoss/lykos/subscription","commits_url":"https://api.github.com/repos/lykoss/lykos/commits{/sha}","git_commits_url":"https://api.github.com/repos/lykoss/lykos/git/commits{/sha}","comments_url":"https://api.github.com/repos/lykoss/lykos/comments{/number}","issue_comment_url":"https://api.github.com/repos/lykoss/lykos/issues/comments{/number}","contents_url":"https://api.github.com/repos/lykoss/lykos/contents/{+path}","compare_url":"https://api.github.com/repos/lykoss/lykos/compare/{base}...{head}","merges_url":"https://api.github.com/repos/lykoss/lykos/merges","archive_url":"https://api.github.com/repos/lykoss/lykos/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/lykoss/lykos/downloads","issues_url":"https://api.github.com/repos/lykoss/lykos/issues{/number}","pulls_url":"https://api.github.com/repos/lykoss/lykos/pulls{/number}","milestones_url":"https://api.github.com/repos/lykoss/lykos/milestones{/number}","notifications_url":"https://api.github.com/repos/lykoss/lykos/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/lykoss/lykos/labels{/name}","releases_url":"https://api.github.com/repos/lykoss/lykos/releases{/id}","created_at":"2014-02-17T17:02:57Z","updated_at":"2016-01-12T0
                 self.plugin = <GitHub GitHub <GitHub.plugin.GitHub object at 0x7f8b84153240>>
                self.headers = <http.client.HTTPMessage object at 0x7f8b89568438>
            self.send_header = <bound method SupyHTTPRequestHandler.send_header of <supybot.httpserver.SupyHTTPRequestHandler object at 0x7f8b84e94080>>
          self.send_response = <bound method SupyHTTPRequestHandler.send_response of <supybot.httpserver.SupyHTTPRequestHandler object at 0x7f8b84e94080>>
            self.end_headers = <bound method SupyHTTPRequestHandler.end_headers of <supybot.httpserver.SupyHTTPRequestHandler object at 0x7f8b84e94080>>
                           f = <function GithubCallback.doPost at 0x7f8b7ec4cd08>
                  self.rfile = <_io.BufferedReader name=86>
                  self.wfile = <socket.SocketIO object at 0x7f8b895647f0>
                logException = <function firewall.<locals>.logException at 0x7f8b7ec4c620>
                        args = (<supybot.httpserver.SupyHTTPRequestHandler object at 0x7f8b84e94080>, '/')
                errorHandler = None


Frame doPost in /home/nyuszika7h/bots/caroline/plugins/GitHub/plugin.py at line 154
                        self = <GitHub.plugin.GithubCallback object at 0x7f8b84e25be0>
                     handler = <supybot.httpserver.SupyHTTPRequestHandler object at 0x7f8b84e94080>
                        path = '/'
                self.headers = <http.client.HTTPMessage object at 0x7f8b89568438>
            self.send_header = <bound method SupyHTTPRequestHandler.send_header of <supybot.httpserver.SupyHTTPRequestHandler object at 0x7f8b84e94080>>
          self.send_response = <bound method SupyHTTPRequestHandler.send_response of <supybot.httpserver.SupyHTTPRequestHandler object at 0x7f8b84e94080>>
            self.end_headers = <bound method SupyHTTPRequestHandler.end_headers of <supybot.httpserver.SupyHTTPRequestHandler object at 0x7f8b84e94080>>
                        form = FieldStorage(None, None, [MiniFieldStorage('payload', '{"pages":[{"page_name":"Home","title":"Home","summary":null,"action":"edited","sha":"40c2918e8594774bb1da2e5b84865a6fe89b3ad8","html_url":"https://github.com/lykoss/lykos/wiki/Home"}],"repository":{"id":16919993,"name":"lykos","full_name":"lykoss/lykos","owner":{"login":"lykoss","id":6707035,"avatar_url":"https://avatars.githubusercontent.com/u/6707035?v=3","gravatar_id":"","url":"https://api.github.com/users/lykoss","html_url":"https://github.com/lykoss","followers_url":"https://api.github.com/users/lykoss/followers","following_url":"https://api.github.com/users/lykoss/following{/other_user}","gists_url":"https://api.github.com/users/lykoss/gists{/gist_id}","starred_url":"https://api.github.com/users/lykoss/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lykoss/subscriptions","organizations_url":"https://api.github.com/users/lykoss/orgs","repos_url":"https://api.github.com/users/lykoss/repos","events_url":"https://api.github.com/users/lykoss/events{/privacy}","received_events_url":"https://api.github.com/users/lykoss/received_events","type":"Organization","site_admin":false},"private":false,"html_url":"https://github.com/lykoss/lykos","description":"Werewolf, the popular detective/social party game (a theme of Mafia)","fork":false,"url":"https://api.github.com/repos/lykoss/lykos","forks_url":"https://api.github.com/repos/lykoss/lykos/forks","keys_url":"https://api.github.com/repos/lykoss/lykos/keys{/key_id}","collaborators_url":"https://api.github.com/repos/lykoss/lykos/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/lykoss/lykos/teams","hooks_url":"https://api.github.com/repos/lykoss/lykos/hooks","issue_events_url":"https://api.github.com/repos/lykoss/lykos/issues/events{/number}","events_url":"https://api.github.com/repos/lykoss/lykos/events","assignees_url":"https://api.github.com/repos/lykoss/lykos/assignees{/user}","branches_url":"https://api.github.com/repos/lykoss/lykos/branches{/branch}","tags_url":"https://api.github.com/repos/lykoss/lykos/tags","blobs_url":"https://api.github.com/repos/lykoss/lykos/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/lykoss/lykos/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/lykoss/lykos/git/refs{/sha}","trees_url":"https://api.github.com/repos/lykoss/lykos/git/trees{/sha}","statuses_url":"https://api.github.com/repos/lykoss/lykos/statuses/{sha}","languages_url":"https://api.github.com/repos/lykoss/lykos/languages","stargazers_url":"https://api.github.com/repos/lykoss/lykos/stargazers","contributors_url":"https://api.github.com/repos/lykoss/lykos/contributors","subscribers_url":"https://api.github.com/repos/lykoss/lykos/subscribers","subscription_url":"https://api.github.com/repos/lykoss/lykos/subscription","commits_url":"https://api.github.com/repos/lykoss/lykos/commits{/sha}","git_commits_url":"https://api.github.com/repos/lykoss/lykos/git/commits{/sha}","comments_url":"https://api.github.com/repos/lykoss/lykos/comments{/number}","issue_comment_url":"https://api.github.com/repos/lykoss/lykos/issues/comments{/number}","contents_url":"https://api.github.com/repos/lykoss/lykos/contents/{+path}","compare_url":"https://api.github.com/repos/lykoss/lykos/compare/{base}...{head}","merges_url":"https://api.github.com/repos/lykoss/lykos/merges","archive_url":"https://api.github.com/repos/lykoss/lykos/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/lykoss/lykos/downloads","issues_url":"https://api.github.com/repos/lykoss/lykos/issues{/number}","pulls_url":"https://api.github.com/repos/lykoss/lykos/pulls{/number}","milestones_url":"https://api.github.com/repos/lykoss/lykos/milestones{/number}","notifications_url":"https://api.github.com/repos/lykoss/lykos/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/lykoss/lykos/labels{/name}","releases_url":"https://api.github.com/repos/lykoss/lykos/releases{/id}","created_at":"2014-02-17T17:02:57Z","updated_at":"2016-01-12T01:15:14Z"
                  self.rfile = <_io.BufferedReader name=86>
                       event = 'gollum'
                  self.wfile = <socket.SocketIO object at 0x7f8b895647f0>
                     headers = {'X-Real-IP': '192.30.252.42', 'Accept': '*/*', 'X-Forwarded-For': '192.30.252.42', 'X-GitHub-Delivery': '28a12680-b9e4-11e5-870f-9ca2b3e7f611', 'User-Agent': 'GitHub-Hookshot/35ff2c9', 'X-GitHub-Event': 'gollum', 'content-type': 'application/x-www-form-urlencoded', 'Connection': 'close', 'Content-Length': '8446', 'Host': 'cl.cadoth.net'}
                 self.plugin = <GitHub GitHub <GitHub.plugin.GitHub object at 0x7f8b84153240>>


Frame onPayload in /home/nyuszika7h/bots/caroline/plugins/GitHub/plugin.py at line 346
                        self = <GitHub.plugin.GitHub.announce object at 0x7f8b84f06518>
                    self.log = <supybot.log.Logger object at 0x7f8b8944c160>
                     network = 'freenode'
                    self.cbs = []
                     headers = {'X-Real-IP': '192.30.252.42', 'Accept': '*/*', 'X-Forwarded-For': '192.30.252.42', 'X-GitHub-Delivery': '28a12680-b9e4-11e5-870f-9ca2b3e7f611', 'User-Agent': 'GitHub-Hookshot/35ff2c9', 'X-GitHub-Event': 'gollum', 'content-type': 'application/x-www-form-urlencoded', 'Connection': 'close', 'Content-Length': '8446', 'Host': 'cl.cadoth.net'}
                    payload2 = {'organization': {'description': '', 'login': 'lykoss', 'members_url': 'https://api.github.com/orgs/lykoss/members{/member}', 'public_members_url': 'https://api.github.com/orgs/lykoss/public_members{/member}', 'events_url': 'https://api.github.com/orgs/lykoss/events', 'url': 'https://api.github.com/orgs/lykoss', 'avatar_url': 'https://avatars.githubusercontent.com/u/6707035?v=3', 'id': 6707035, 'repos_url': 'https://api.github.com/orgs/lykoss/repos'}, 'pages': [{'summary': None, 'action': 'edited', 'page_name': 'Home', 'title': 'Home', 'sha': '40c2918e8594774bb1da2e5b84865a6fe89b3ad8', 'html_url': 'https://github.com/lykoss/lykos/wiki/Home'}], 'repository': {'teams_url': 'https://api.github.com/repos/lykoss/lykos/teams', 'description': 'Werewolf, the popular detective/social party game (a theme of Mafia)', 'compare_url': 'https://api.github.com/repos/lykoss/lykos/compare/{base}...{head}', 'watchers_count': 46, 'git_refs_url': 'https://api.github.com/repos/lykoss/lykos/git/refs{/sha}', 'labels_url': 'https://api.github.com/repos/lykoss/lykos/labels{/name}', 'private': False, 'fork': False, 'mirror_url': None, 'git_tags_url': 'https://api.github.com/repos/lykoss/lykos/git/tags{/sha}', 'commits_url': 'https://api.github.com/repos/lykoss/lykos/commits{/sha}', 'clone_url': 'https://github.com/lykoss/lykos.git', 'contributors_url': 'https://api.github.com/repos/lykoss/lykos/contributors', 'subscription_url': 'https://api.github.com/repos/lykoss/lykos/subscription', 'tags_url': 'https://api.github.com/repos/lykoss/lykos/tags', 'homepage': 'http://wolf.xnrand.com/', 'downloads_url': 'https://api.github.com/repos/lykoss/lykos/downloads', 'statuses_url': 'https://api.github.com/repos/lykoss/lykos/statuses/{sha}', 'has_wiki': True, 'trees_url': 'https://api.github.com/repos/lykoss/lykos/git/trees{/sha}', 'id': 16919993, 'forks_count': 33, 'open_issues': 22, 'languages_url': 'https://api.github.com/repos/lykoss/lykos/languages', 'issues_url': 'https://api.github.com/repos/lykoss/lykos/issues{/number}', 'pulls_url': 'https://api.github.com/repos/lykoss/lykos/pulls{/number}', 'git_url': 'git://github.com/lykoss/lykos.git', 'events_url': 'https://api.github.com/repos/lykoss/lykos/events', 'stargazers_count': 46, 'owner': {'followers_url': 'https://api.github.com/users/lykoss/followers', 'subscriptions_url': 'https://api.github.com/users/lykoss/subscriptions', 'avatar_url': 'https://avatars.githubusercontent.com/u/6707035?v=3', 'gists_url': 'https://api.github.com/users/lykoss/gists{/gist_id}', 'url': 'https://api.github.com/users/lykoss', 'following_url': 'https://api.github.com/users/lykoss/following{/other_user}', 'starred_url': 'https://api.github.com/users/lykoss/starred{/owner}{/repo}', 'organizations_url': 'https://api.github.com/users/lykoss/orgs', 'html_url': 'https://github.com/lykoss', 'repos_url': 'https://api.github.com/users/lykoss/repos', 'login': 'lykoss', 'gravatar_id': '', 'id': 6707035, 'events_url': 'https://api.github.com/users/lykoss/events{/privacy}', 'type': 'Organization', 'received_events_url': 'https://api.github.com/users/lykoss/received_events', 'site_admin': False}, 'has_downloads': True, 'has_pages': False, 'pushed_at': '2016-01-12T04:56:16Z', 'forks': 33, 'branches_url': 'https://api.github.com/repos/lykoss/lykos/branches{/branch}', 'language': 'Python', 'created_at': '2014-02-17T17:02:57Z', 'git_commits_url': 'https://api.github.com/repos/lykoss/lykos/git/commits{/sha}', 'updated_at': '2016-01-12T01:15:14Z', 'notifications_url': 'https://api.github.com/repos/lykoss/lykos/notifications{?since,all,participating}', 'milestones_url': 'https://api.github.com/repos/lykoss/lykos/milestones{/number}', 'merges_url': 'https://api.github.com/repos/lykoss/lykos/merges', 'blobs_url': 'https://api.github.com/repos/lykoss/lykos/git/blobs{/sha}', 'default_branch': 'master', 'open_issues_count': 22, 'forks_url': 'https://api.github.com/repos/lykoss/lykos/forks', 'name': 'lykos', 'size': 4634, 'releases_url': 'https://api.github.com/repos/lykoss/lykos/releases{/id}', 'archive_url': 'https:/
                   announces = [('shalture/shalture', 'freenode', '#shalture'), ('nyuszika7h/sandbox', 'freenode', '##aelita'), ('gnudeb/ircah', 'freenode', '##ircah-dev'), ('lykoss/*', 'freenode', '##werewolf-dev'), ('ircah/*', 'freenode', '##ircah-dev'), ('nyuszika7h/*', 'freenode', '##nyuszika7h')]
                      dbRepo = 'nyuszika7h/*'
        self._MetaSynchronized_rlock = <_thread.RLock owner=0 count=0>
                        page = {'summary': None, 'action': 'edited', 'page_name': 'Home', 'title': 'Home', 'sha': '40c2918e8594774bb1da2e5b84865a6fe89b3ad8', 'html_url': 'https://github.com/lykoss/lykos/wiki/Home'}
               repoAnnounces = [('freenode', '##werewolf-dev')]
                       event = 'gollum'
                     payload = {'organization': {'description': '', 'login': 'lykoss', 'members_url': 'https://api.github.com/orgs/lykoss/members{/member}', 'public_members_url': 'https://api.github.com/orgs/lykoss/public_members{/member}', 'events_url': 'https://api.github.com/orgs/lykoss/events', 'url': 'https://api.github.com/orgs/lykoss', 'avatar_url': 'https://avatars.githubusercontent.com/u/6707035?v=3', 'id': 6707035, 'repos_url': 'https://api.github.com/orgs/lykoss/repos'}, 'repository': {'teams_url': 'https://api.github.com/repos/lykoss/lykos/teams', 'description': 'Werewolf, the popular detective/social party game (a theme of Mafia)', 'compare_url': 'https://api.github.com/repos/lykoss/lykos/compare/{base}...{head}', 'watchers_count': 46, 'git_refs_url': 'https://api.github.com/repos/lykoss/lykos/git/refs{/sha}', 'labels_url': 'https://api.github.com/repos/lykoss/lykos/labels{/name}', 'private': False, 'fork': False, 'mirror_url': None, 'git_tags_url': 'https://api.github.com/repos/lykoss/lykos/git/tags{/sha}', 'commits_url': 'https://api.github.com/repos/lykoss/lykos/commits{/sha}', 'clone_url': 'https://github.com/lykoss/lykos.git', 'contributors_url': 'https://api.github.com/repos/lykoss/lykos/contributors', 'subscription_url': 'https://api.github.com/repos/lykoss/lykos/subscription', 'tags_url': 'https://api.github.com/repos/lykoss/lykos/tags', 'homepage': 'http://wolf.xnrand.com/', 'downloads_url': 'https://api.github.com/repos/lykoss/lykos/downloads', 'statuses_url': 'https://api.github.com/repos/lykoss/lykos/statuses/{sha}', 'has_wiki': True, 'trees_url': 'https://api.github.com/repos/lykoss/lykos/git/trees{/sha}', 'id': 16919993, 'forks_count': 33, 'open_issues': 22, 'languages_url': 'https://api.github.com/repos/lykoss/lykos/languages', 'issues_url': 'https://api.github.com/repos/lykoss/lykos/issues{/number}', 'pulls_url': 'https://api.github.com/repos/lykoss/lykos/pulls{/number}', 'git_url': 'git://github.com/lykoss/lykos.git', 'events_url': 'https://api.github.com/repos/lykoss/lykos/events', 'stargazers_count': 46, 'owner': {'followers_url': 'https://api.github.com/users/lykoss/followers', 'subscriptions_url': 'https://api.github.com/users/lykoss/subscriptions', 'avatar_url': 'https://avatars.githubusercontent.com/u/6707035?v=3', 'gists_url': 'https://api.github.com/users/lykoss/gists{/gist_id}', 'url': 'https://api.github.com/users/lykoss', 'following_url': 'https://api.github.com/users/lykoss/following{/other_user}', 'starred_url': 'https://api.github.com/users/lykoss/starred{/owner}{/repo}', 'organizations_url': 'https://api.github.com/users/lykoss/orgs', 'html_url': 'https://github.com/lykoss', 'repos_url': 'https://api.github.com/users/lykoss/repos', 'login': 'lykoss', 'gravatar_id': '', 'id': 6707035, 'events_url': 'https://api.github.com/users/lykoss/events{/privacy}', 'type': 'Organization', 'received_events_url': 'https://api.github.com/users/lykoss/received_events', 'site_admin': False}, 'has_downloads': True, 'has_pages': False, 'pushed_at': '2016-01-12T04:56:16Z', 'forks': 33, 'branches_url': 'https://api.github.com/repos/lykoss/lykos/branches{/branch}', 'language': 'Python', 'created_at': '2014-02-17T17:02:57Z', 'git_commits_url': 'https://api.github.com/repos/lykoss/lykos/git/commits{/sha}', 'updated_at': '2016-01-12T01:15:14Z', 'notifications_url': 'https://api.github.com/repos/lykoss/lykos/notifications{?since,all,participating}', 'milestones_url': 'https://api.github.com/repos/lykoss/lykos/milestones{/number}', 'merges_url': 'https://api.github.com/repos/lykoss/lykos/merges', 'blobs_url': 'https://api.github.com/repos/lykoss/lykos/git/blobs{/sha}', 'default_branch': 'master', 'open_issues_count': 22, 'forks_url': 'https://api.github.com/repos/lykoss/lykos/forks', 'name': 'lykos', 'size': 4634, 'releases_url': 'https://api.github.com/repos/lykoss/lykos/releases{/id}', 'archive_url': 'https://api.github.com/repos/lykoss/lykos/{archive_format}{/ref}', 'keys_url': 'https://api.github.com/repos/lykoss/lykos/keys{/key_id}', 'contents_url': 'https://api.github.com/repos/lykoss/lykos/conten
                     channel = '##werewolf-dev'
                         irc = <irclib.Irc object for freenode>
                       pages = [{'summary': None, 'action': 'edited', 'page_name': 'Home', 'title': 'Home', 'sha': '40c2918e8594774bb1da2e5b84865a6fe89b3ad8', 'html_url': 'https://github.com/lykoss/lykos/wiki/Home'}]
                        repo = 'lykoss/lykos'
                 self.plugin = <GitHub GitHub <GitHub.plugin.GitHub object at 0x7f8b84153240>>


Frame _createPrivmsg in /home/nyuszika7h/bots/caroline/plugins/GitHub/plugin.py at line 233
                        bold = <function bold at 0x7f8b89a42bf8>
                        self = <GitHub.plugin.GitHub.announce object at 0x7f8b84f06518>
                         key = 'repository__clone_url'
                     format_ = 'echo "[\x0310$repository__name\x03]" \x0307$sender__login\x03 $__page__action wiki page \x0309$__page__title\x03 \x0313$__page__html_url__tiny\x03'
                 self.plugin = <GitHub GitHub <GitHub.plugin.GitHub object at 0x7f8b84153240>>
                    self.cbs = []
                     payload = {'organization': {'description': '', 'login': 'lykoss', 'members_url': 'https://api.github.com/orgs/lykoss/members{/member}', 'public_members_url': 'https://api.github.com/orgs/lykoss/public_members{/member}', 'events_url': 'https://api.github.com/orgs/lykoss/events', 'url': 'https://api.github.com/orgs/lykoss', 'avatar_url': 'https://avatars.githubusercontent.com/u/6707035?v=3', 'id': 6707035, 'repos_url': 'https://api.github.com/orgs/lykoss/repos'}, 'pages': [{'summary': None, 'action': 'edited', 'page_name': 'Home', 'title': 'Home', 'sha': '40c2918e8594774bb1da2e5b84865a6fe89b3ad8', 'html_url': 'https://github.com/lykoss/lykos/wiki/Home'}], 'repository': {'teams_url': 'https://api.github.com/repos/lykoss/lykos/teams', 'description': 'Werewolf, the popular detective/social party game (a theme of Mafia)', 'compare_url': 'https://api.github.com/repos/lykoss/lykos/compare/{base}...{head}', 'watchers_count': 46, 'git_refs_url': 'https://api.github.com/repos/lykoss/lykos/git/refs{/sha}', 'labels_url': 'https://api.github.com/repos/lykoss/lykos/labels{/name}', 'private': False, 'fork': False, 'mirror_url': None, 'git_tags_url': 'https://api.github.com/repos/lykoss/lykos/git/tags{/sha}', 'commits_url': 'https://api.github.com/repos/lykoss/lykos/commits{/sha}', 'clone_url': 'https://github.com/lykoss/lykos.git', 'contributors_url': 'https://api.github.com/repos/lykoss/lykos/contributors', 'subscription_url': 'https://api.github.com/repos/lykoss/lykos/subscription', 'tags_url': 'https://api.github.com/repos/lykoss/lykos/tags', 'homepage': 'http://wolf.xnrand.com/', 'downloads_url': 'https://api.github.com/repos/lykoss/lykos/downloads', 'statuses_url': 'https://api.github.com/repos/lykoss/lykos/statuses/{sha}', 'has_wiki': True, 'trees_url': 'https://api.github.com/repos/lykoss/lykos/git/trees{/sha}', 'id': 16919993, 'forks_count': 33, 'open_issues': 22, 'languages_url': 'https://api.github.com/repos/lykoss/lykos/languages', 'issues_url': 'https://api.github.com/repos/lykoss/lykos/issues{/number}', 'pulls_url': 'https://api.github.com/repos/lykoss/lykos/pulls{/number}', 'git_url': 'git://github.com/lykoss/lykos.git', 'events_url': 'https://api.github.com/repos/lykoss/lykos/events', 'stargazers_count': 46, 'owner': {'followers_url': 'https://api.github.com/users/lykoss/followers', 'subscriptions_url': 'https://api.github.com/users/lykoss/subscriptions', 'avatar_url': 'https://avatars.githubusercontent.com/u/6707035?v=3', 'gists_url': 'https://api.github.com/users/lykoss/gists{/gist_id}', 'url': 'https://api.github.com/users/lykoss', 'following_url': 'https://api.github.com/users/lykoss/following{/other_user}', 'starred_url': 'https://api.github.com/users/lykoss/starred{/owner}{/repo}', 'organizations_url': 'https://api.github.com/users/lykoss/orgs', 'html_url': 'https://github.com/lykoss', 'repos_url': 'https://api.github.com/users/lykoss/repos', 'login': 'lykoss', 'gravatar_id': '', 'id': 6707035, 'events_url': 'https://api.github.com/users/lykoss/events{/privacy}', 'type': 'Organization', 'received_events_url': 'https://api.github.com/users/lykoss/received_events', 'site_admin': False}, 'has_downloads': True, 'has_pages': False, 'pushed_at': '2016-01-12T04:56:16Z', 'forks': 33, 'branches_url': 'https://api.github.com/repos/lykoss/lykos/branches{/branch}', 'language': 'Python', 'created_at': '2014-02-17T17:02:57Z', 'git_commits_url': 'https://api.github.com/repos/lykoss/lykos/git/commits{/sha}', 'updated_at': '2016-01-12T01:15:14Z', 'notifications_url': 'https://api.github.com/repos/lykoss/lykos/notifications{?since,all,participating}', 'milestones_url': 'https://api.github.com/repos/lykoss/lykos/milestones{/number}', 'merges_url': 'https://api.github.com/repos/lykoss/lykos/merges', 'blobs_url': 'https://api.github.com/repos/lykoss/lykos/git/blobs{/sha}', 'default_branch': 'master', 'open_issues_count': 22, 'forks_url': 'https://api.github.com/repos/lykoss/lykos/forks', 'name': 'lykos', 'size': 4634, 'releases_url': 'https://api.github.com/repos/lykoss/lykos/releases{/id}', 'archive_url': 'https:/
                      hidden = None
                       value = 'https://github.com/lykoss/lykos.git'
                       event = 'gollum'
                        repl = {'repository__clone_url': 'https://github.com/lykoss/lykos.git', 'organization__public_members_url': 'https://api.github.com/orgs/lykoss/public_members{/member}', 'repository__id': 16919993, 'repository__has_issues': True, 'repository__git_commits_url': 'https://api.github.com/repos/lykoss/lykos/git/commits{/sha}', 'repository__homepage': 'http://wolf.xnrand.com/', 'repository__owner__avatar_url': 'https://avatars.githubusercontent.com/u/6707035?v=3', 'repository__full_name': 'lykoss/lykos', 'repository__stargazers_count': 46, 'repository__languages_url': 'https://api.github.com/repos/lykoss/lykos/languages', 'sender__gists_url': 'https://api.github.com/users/timson622222/gists{/gist_id}', 'repository__subscribers_url': 'https://api.github.com/repos/lykoss/lykos/subscribers', 'sender__subscriptions_url': 'https://api.github.com/users/timson622222/subscriptions', 'sender__events_url': 'https://api.github.com/users/timson622222/events{/privacy}', 'repository__watchers_count': 46, 'repository__git_tags_url': 'https://api.github.com/repos/lykoss/lykos/git/tags{/sha}', 'repository__owner__repos_url': 'https://api.github.com/users/lykoss/repos', 'repository__blobs_url': 'https://api.github.com/repos/lykoss/lykos/git/blobs{/sha}', 'repository__compare_url': 'https://api.github.com/repos/lykoss/lykos/compare/{base}...{head}', 'repository__default_branch': 'master', 'repository__archive_url': 'https://api.github.com/repos/lykoss/lykos/{archive_format}{/ref}', 'sender__login': 'timson622222', 'repository__issue_comment_url': 'https://api.github.com/repos/lykoss/lykos/issues/comments{/number}', 'repository__owner__followers_url': 'https://api.github.com/users/lykoss/followers', 'organization__repos_url': 'https://api.github.com/orgs/lykoss/repos', 'repository__owner__starred_url': 'https://api.github.com/users/lykoss/starred{/owner}{/repo}', 'repository__subscription_url': 'https://api.github.com/repos/lykoss/lykos/subscription', 'repository__issues_url': 'https://api.github.com/repos/lykoss/lykos/issues{/number}', 'repository__size': 4634, 'repository__owner__events_url': 'https://api.github.com/users/lykoss/events{/privacy}', 'repository__notifications_url': 'https://api.github.com/repos/lykoss/lykos/notifications{?since,all,participating}', 'repository__pulls_url': 'https://api.github.com/repos/lykoss/lykos/pulls{/number}', 'repository__teams_url': 'https://api.github.com/repos/lykoss/lykos/teams', 'repository__created_at': '2014-02-17T17:02:57Z', 'repository__stargazers_url': 'https://api.github.com/repos/lykoss/lykos/stargazers', 'repository__forks_count': 33, 'repository__assignees_url': 'https://api.github.com/repos/lykoss/lykos/assignees{/user}', 'repository__forks_url': 'https://api.github.com/repos/lykoss/lykos/forks', 'repository__private': False, 'repository__milestones_url': 'https://api.github.com/repos/lykoss/lykos/milestones{/number}', 'organization__events_url': 'https://api.github.com/orgs/lykoss/events', 'repository__trees_url': 'https://api.github.com/repos/lykoss/lykos/git/trees{/sha}', 'repository__fork': False, 'pages': [{'summary': None, 'action': 'edited', 'page_name': 'Home', 'title': 'Home', 'sha': '40c2918e8594774bb1da2e5b84865a6fe89b3ad8', 'html_url': 'https://github.com/lykoss/lykos/wiki/Home'}], '__page__title': 'Home', 'repository__has_wiki': True, 'repository__owner__type': 'Organization', 'repository__has_pages': False, '__page__html_url': 'https://github.com/lykoss/lykos/wiki/Home', 'sender__url': 'https://api.github.com/users/timson622222', '__page__action': 'edited', 'repository__owner__subscriptions_url': 'https://api.github.com/users/lykoss/subscriptions', 'repository__html_url': 'https://github.com/lykoss/lykos', 'repository__owner__gravatar_id': '', 'repository__owner__id': 6707035, 'repository__ssh_url': 'git@github.com:lykoss/lykos.git', 'repository__events_url': 'https://api.github.com/repos/lykoss/lykos/events', 'organization__avatar_url': 'https://avatars.githubusercontent.com/u/6707035?v=3', 'organization__login': 'lykoss', 'sender__following_url': 'http
                     channel = '##werewolf-dev'
                         irc = <irclib.Irc object for freenode>
                    self.log = <supybot.log.Logger object at 0x7f8b8944c160>
                        host = 'github.com'
        self._MetaSynchronized_rlock = <_thread.RLock owner=0 count=0>


Frame _shorten_url in /home/nyuszika7h/bots/caroline/plugins/GitHub/plugin.py at line 214
                    self.log = <supybot.log.Logger object at 0x7f8b8944c160>
                        self = <GitHub.plugin.GitHub.announce object at 0x7f8b84f06518>
                        data = b'url=https%3A%2F%2Fgithub.com%2Flykoss%2Flykos.git'
                 self.plugin = <GitHub GitHub <GitHub.plugin.GitHub object at 0x7f8b84153240>>
                    self.cbs = []
                         url = 'https://github.com/lykoss/lykos.git'
                           f = <http.client.HTTPResponse object at 0x7f8b840602b0>
        self._MetaSynchronized_rlock = <_thread.RLock owner=0 count=0>

+-----------------------+
| End of locals display |
+-----------------------+
```

**Comment by ProgVal** [comment]
Wrong repo.
Also, please provide the payload (you can find it in GitHub's webhook interface).
