### ISSUE TITLE
[regression] 2016.02.23 doesn't support SSL connections even without SSL certificate validation on Python 2.7.6

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1217]
```pytb
INFO 2016-02-24T07:22:01 supybot Completed daemonization. Current PID: 2043
INFO 2016-02-24T07:22:01 supybot Connecting to chat.freenode.net:6697.
WARNING 2016-02-24T07:22:01 supybot Not checking SSL certificates, connections are vulnerable to man-in-the-middle attacks. Set supybot.protocols.ssl.verifyCertificates to "true" to enable validity checks.
ERROR 2016-02-24T07:22:01 supybot Exception connecting to freenode:
Traceback (most recent call last):
  File "/home/meetingology/.local/lib/python2.7/site-packages/supybot/plugins/Owner/plugin.py", line 125, in __init__
    self._connect(network)
  File "/home/meetingology/.local/lib/python2.7/site-packages/supybot/plugins/Owner/plugin.py", line 165, in _connect
    driver = drivers.newDriver(newIrc)
  File "/home/meetingology/.local/lib/python2.7/site-packages/supybot/drivers/__init__.py", line 190, in newDriver
    driver = driverModule.Driver(irc)
  File "/home/meetingology/.local/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 85, in __init__
    self.connect()
  File "/home/meetingology/.local/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 218, in connect
    self.reconnect(reset=False, **kwargs)
  File "/home/meetingology/.local/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 281, in reconnect
    self.starttls()
  File "/home/meetingology/.local/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 376, in starttls
    ca_file=network_config.ssl.authorityCertificate(),
  File "/home/meetingology/.local/lib/python2.7/site-packages/supybot/utils/net.py", line 169, in ssl_wrap_socket
    ssl_version=ssl.ssl.PROTOCOL_TLSv1, verify_mode=ssl.CERT_NONE)
AttributeError: 'module' object has no attribute 'ssl'
ERROR 2016-02-24T07:22:01 supybot Exception id: 0xf6f94
ERROR 2016-02-24T07:22:01 supybot Could not connect to freenode: 'module' object has no attribute 'ssl'.
```

* Python 2.7.6
* Ubuntu 14.04.4 LTS

Bot downgraded to 2016-01-06 which is the latest working version. Updating to Python 3 is not possible yet [as the plugin which the whole bot is ran for is not Python 3 comatible.](https://bugs.launchpad.net/ubuntu-bots/+bug/1531427)

**Comment by ProgVal** [comment]
I believe this is fixed in 2016.02.24.

**Comment by ProgVal** [comment]
PS: sorry for the delay, my mail server was broken and I did not notice it

**Comment by Mikaela** [comment]
Seems to be fixed.
