### ISSUE TITLE
Uncaught exception in ChannelLogger.__call__

### ISSUE THREAD

**Issue by damascene** [ProgVal/Limnoria#1222]
An error seems to happen to ChanLogger plugin after ChanReg welcome message

```
DEBUG 2016-02-27T10:35:04 supybot Incoming message (freenode): :kornbluth.freenode.net 366 LinuxACBot ##programming-ar :End of /NAMES list.
DEBUG 2016-02-27T10:35:04 supybot Incoming message (freenode): :LinuxACBot!~limnoria@unaffiliated/uaa/bot/linuxacbot JOIN #linuxac-social LinuxACBot :LinuxACBot
DEBUG 2016-02-27T10:35:04 supybot restoring 1 items for #linuxac-social
DEBUG 2016-02-27T10:35:04 supybot findCallbacksForArgs: [(<Utilities Utilities <Utilities.plugin.Utilities object at 0xb6687f8c>>, ['echo'])]
INFO 2016-02-27T10:35:04 supybot echo called on #linuxac-social by "LinuxACBot!uaa@gateway/shell/panicbnc/x-uzztrenyohvlgzim".
DEBUG 2016-02-27T10:35:04 supybot args before <context for text>: ['Hello', 'LinuxACBot,', 'welcome', 'back', 'in', '#linuxac-social']
DEBUG 2016-02-27T10:35:04 supybot args after <context for text>: []
DEBUG 2016-02-27T10:35:04 supybot State before call: State(args=['Hello LinuxACBot, welcome back in #linuxac-social'], kwargs={}, channel=None)
ERROR 2016-02-27T10:35:04 supybot Uncaught exception in ChannelLogger.__call__:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.4/site-packages/supybot/log.py", line 362, in m
    return f(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.4/site-packages/supybot/irclib.py", line 132, in __call__
    method(irc, msg)
  File "/home/user/.local/lib/python3.4/site-packages/supybot/plugins/ChannelLogger/plugin.py", line 174, in doPrivmsg
    (recipients, text) = msg.args
ValueError: too many values to unpack (expected 2)
ERROR 2016-02-27T10:35:04 supybot Exception id: 0x53fa3
DEBUG 2016-02-27T10:35:04 supybot Limnoria version: 0.83.4.1+limnoria installed on 2016-02-22T17-37-42

Locals by frame, innermost last:


Frame m in /home/user/.local/lib/python3.4/site-packages/supybot/log.py at line 366
                      kwargs = {}
        self._MetaSynchronized_rlock = <_thread.RLock owner=0 count=0>
                    self.cbs = []
            self.classModule = <module 'ChannelLogger' from '/home/user/.local/lib/python3.4/site-packages/supybot/plugins/ChannelLogger/__init__.py'>
                           f = <function IrcCallback.__call__ at 0xb6ae0f14>
                errorHandler = None
                        self = <ChannelLogger ChannelLogger <ChannelLogger.plugin.ChannelLogger object at 0xb67eddcc>>
                   self.logs = {<supybot.callbacks.ReplyIrcProxy object at 0xb6643d6c>: IrcDict({'##programming-ar': ('##programming-ar', <_io.TextIOWrapper name='/home/user/runbot/logs/ChannelLogger/freenode/##programming-ar/##programming-ar.2016-02-27.log' mode='a' encoding='utf-8'>), '##namespace': ('##namespace', <_io.TextIOWrapper name='/home/user/runbot/logs/ChannelLogger/freenode/##namespace/##namespace.2016-02-27.log' mode='a' encoding='utf-8'>)})}
                self.flusher = <bound method ChannelLogger.flush of <ChannelLogger ChannelLogger <ChannelLogger.plugin.ChannelLogger object at 0xb67eddcc>>>
                logException = <function firewall.<locals>.logException at 0xb6a71194>
        self._PluginMixin__parent = <super: <class 'PluginMixin'>, <ChannelLogger object>>
        self._ChannelLogger__parent = <super: <class 'ChannelLogger'>, <ChannelLogger object>>
                        args = (<supybot.callbacks.ReplyIrcProxy object at 0xb664368c>, IrcMsg(prefix="LinuxACBot!uaa@gateway/shell/panicbnc/x-uzztrenyohvlgzim", command="PRIVMSG", args=('#linuxac-social', 'LinuxACBot', 'LinuxACBot')))
                    self.log = <supybot.log.Logger object at 0xb6b1b26c>


Frame __call__ in /home/user/.local/lib/python3.4/site-packages/supybot/irclib.py at line 132
        self._MetaSynchronized_rlock = <_thread.RLock owner=0 count=0>
                    self.cbs = []

                    self.log = <supybot.log.Logger object at 0xb6b1b26c>
                      method = <bound method ChannelLogger.doPrivmsg of <ChannelLogger ChannelLogger <ChannelLogger.plugin.ChannelLogger object at 0xb67eddcc>>>
                        self = <ChannelLogger ChannelLogger <ChannelLogger.plugin.ChannelLogger object at 0xb67eddcc>>
                   self.logs = {<supybot.callbacks.ReplyIrcProxy object at 0xb6643d6c>: IrcDict({'##programming-ar': ('##programming-ar', <_io.TextIOWrapper name='/home/user/runbot/logs/ChannelLogger/freenode/##programming-ar/##programming-ar.2016-02-27.log' mode='a' encoding='utf-8'>), '##namespace': ('##namespace', <_io.TextIOWrapper name='/home/user/runbot/logs/ChannelLogger/freenode/##namespace/##namespace.2016-02-27.log' mode='a' encoding='utf-8'>)})}
        self._PluginMixin__parent = <super: <class 'PluginMixin'>, <ChannelLogger object>>
        self._ChannelLogger__parent = <super: <class 'ChannelLogger'>, <ChannelLogger object>>
                         msg = IrcMsg(prefix="LinuxACBot!uaa@gateway/shell/panicbnc/x-uzztrenyohvlgzim", command="PRIVMSG", args=('#linuxac-social', 'LinuxACBot', 'LinuxACBot'))
                         irc = <supybot.callbacks.ReplyIrcProxy object at 0xb664368c>
                self.flusher = <bound method ChannelLogger.flush of <ChannelLogger ChannelLogger <ChannelLogger.plugin.ChannelLogger object at 0xb67eddcc>>>
            self.classModule = <module 'ChannelLogger' from '/home/user/.local/lib/python3.4/site-packages/supybot/plugins/ChannelLogger/__init__.py'>


Frame doPrivmsg in /home/user/.local/lib/python3.4/site-packages/supybot/plugins/ChannelLogger/plugin.py at line 174
                   self.logs = {<supybot.callbacks.ReplyIrcProxy object at 0xb6643d6c>: IrcDict({'##programming-ar': ('##programming-ar', <_io.TextIOWrapper name='/home/user/runbot/logs/ChannelLogger/freenode/##programming-ar/##programming-ar.2016-02-27.log' mode='a' encoding='utf-8'>), '##namespace': ('##namespace', <_io.TextIOWrapper name='/home/user/runbot/logs/ChannelLogger/freenode/##namespace/##namespace.2016-02-27.log' mode='a' encoding='utf-8'>)})}
        self._MetaSynchronized_rlock = <_thread.RLock owner=0 count=0>
                self.flusher = <bound method ChannelLogger.flush of <ChannelLogger ChannelLogger <ChannelLogger.plugin.ChannelLogger object at 0xb67eddcc>>>
                    self.cbs = []
            self.classModule = <module 'ChannelLogger' from '/home/user/.local/lib/python3.4/site-packages/supybot/plugins/ChannelLogger/__init__.py'>
        self._PluginMixin__parent = <super: <class 'PluginMixin'>, <ChannelLogger object>>
        self._ChannelLogger__parent = <super: <class 'ChannelLogger'>, <ChannelLogger object>>
                         msg = IrcMsg(prefix="LinuxACBot!uaa@gateway/shell/panicbnc/x-uzztrenyohvlgzim", command="PRIVMSG", args=('#linuxac-social', 'LinuxACBot', 'LinuxACBot'))
                    self.log = <supybot.log.Logger object at 0xb6b1b26c>
                         irc = <supybot.callbacks.ReplyIrcProxy object at 0xb664368c>
                        self = <ChannelLogger ChannelLogger <ChannelLogger.plugin.ChannelLogger object at 0xb67eddcc>>

+-----------------------+
| End of locals display |
+-----------------------+


DEBUG 2016-02-27T10:35:04 supybot Incoming message (freenode): :kornbluth.freenode.net 332 LinuxACBot #linuxac-social :القناة الإجتماعية لمنتدى مجتمع لينكس العربي Linux Arab Community Social Channel | http://www.linuxac.org
DEBUG 2016-02-27T10:35:04 supybot Irc.takeMsg throttling.
DEBUG 2016-02-27T10:35:04 supybot Irc.takeMsg throttling.
DEBUG 2016-02-27T10:35:04 supybot Irc.takeMsg throttling.

```

**Comment by ProgVal** [comment]
Is Chantracker loaded?

**Comment by damascene** [comment]
no

**Comment by ProgVal** [comment]
Oh sorry, I confused ChanReg and ChanTracker.

I think I already reported that issue to @ncoevoet, try to update ChanReg to see if he fixed it.
Otherwise, open an issue to his bug tracker
