### ISSUE TITLE
Seen can't deal with UTF8

### ISSUE THREAD

**Issue by weedy** [ProgVal/Limnoria#1230]
```
DEBUG 2016-03-17T21:51:15 supybot Finished writing registry file.
ERROR 2016-03-17T21:51:15 supybot Uncaught exception in flusher #8 (<bound method SeenDB.flush of <Seen.plugin.SeenDB object at 0x8e55f8c>>):
Traceback (most recent call last):
  File "/home/weedy/supybot/lib/python2.7/site-packages/supybot/world.py", line 121, in flush
    f()
  File "/home/weedy/supybot/lib/python2.7/site-packages/supybot/plugins/__init__.py", line 272, in flush
    writer.writerow(L)
  File "/home/weedy/supybot/lib/python2.7/site-packages/supybot/utils/file.py", line 176, in write
    return self._fd.write(data)
  File "/usr/lib/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 110: ordinal not in range(128)
ERROR 2016-03-17T21:51:15 supybot Exception id: 0x7875c
DEBUG 2016-03-17T21:51:15 supybot Limnoria version: 2016.02.24

Locals by frame, innermost last:


Frame flush in /home/weedy/supybot/lib/python2.7/site-packages/supybot/world.py at line 123
                           i = 8
                           f = <bound method SeenDB.flush of <Seen.plugin.SeenDB object at 0x8e55f8c>>


Frame flush in /home/weedy/supybot/lib/python2.7/site-packages/supybot/plugins/__init__.py at line 272
               self.filename = '/home/weedy/supybot/data/Seen.any.db'
```

**Comment by weedy** [comment]
This corrupts the database.

**Comment by ProgVal** [comment]
Can you try replacing `fd = codecs.open(self.filename, encoding='utf8')` by `fd = open(self.filename)` in `plugins/__init__.py` ?

**Comment by weedy** [comment]
No change.

https://docs.python.org/2/library/csv.html#examples
The cvs module doesn't seem to support UTF8 by design.
https://github.com/jdunck/python-unicodecsv

**Comment by ProgVal** [comment]
You installed the file and restarted the bot, right?

**Comment by weedy** [comment]
Yes
```
~/supybot $ diff -u ~/Limnoria/plugins/__init__.py lib/python2.7/site-packages/supybot/plugins/__init__.py
--- /home/weedy/Limnoria/plugins/__init__.py    2016-02-14 23:40:44.754382878 -0500
+++ lib/python2.7/site-packages/supybot/plugins/__init__.py     2016-04-07 14:03:58.132098669 -0400
@@ -222,7 +222,8 @@
         ChannelUserDictionary.__init__(self)
         self.filename = filename
         try:
-            fd = codecs.open(self.filename, encoding='utf8')
+           #fd = codecs.open(self.filename, encoding='utf8')
+           fd = codecs.open(self.filename)
         except EnvironmentError as e:
             log.warning('Couldn\'t open %s: %s.', self.filename, e)
             return
~/supybot $ date
Thu Apr  7 14:08:31 EDT 2016
~/supybot $ stat supybot.pid 
  File: ‘supybot.pid’
  Size: 5               Blocks: 8          IO Block: 4096   regular file
Device: fe05h/65029d    Inode: 11780136    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   weedy)   Gid: (  100/   users)
Access: 2016-04-07 14:09:01.476994494 -0400
Modify: 2016-04-07 14:08:54.357192530 -0400
Change: 2016-04-07 14:08:54.357192530 -0400
 Birth: -
```

**Comment by ProgVal** [comment]
Sorry, I don't know what do to then

**Comment by ProgVal** [comment]
In `src/utils/file.py`, replace `self._fd = codecs.open(self.tempFilename, mode, encoding=encoding)` by `self._fd = codecs.open(self.tempFilename, mode, encoding=None)`.
Someone else with the same problem reported it fixed their problem. Can you confirm it works for you too?

**Comment by dequis** [comment]
The suggested change fixes it for me.

How to reproduce:

1. Use python2
2. Add seen plugin to the default config
3. Start bot, join it to a channel
4. Send "á" from another client to the channel
5. ^C
6. Get errors when writing db to disk

**Comment by ProgVal** [comment]
Thanks for the procedure, it helped a lot.

Bug fixed in testing branch.

**Comment by weedy** [comment]
I grabbed the patch from testing. This looks fixed after 24hours.
