### ISSUE TITLE
Network command and 'part' command don't mix well

### ISSUE THREAD

**Issue by GLolol** [ProgVal/Limnoria#1240]
IRC:

```
<~GL> `command r-type part #edm
```

Console:

```
INFO 2016-05-05T16:59:25 part called on #test by "GL!GLolol@escape.the.dreamland.ca".
ERROR 2016-05-05T16:59:25 Uncaught exception in ['part'].
Traceback (most recent call last):
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/callbacks.py", line 1283, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/callbacks.py", line 1260, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/commands.py", line 1080, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/plugins/Channel/plugin.py", line 972, in part
    hostmask = irc.state.nickToHostmask(msg.nick)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/irclib.py", line 424, in nickToHostmask
    return self.nicksToHostmasks[nick]
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/utils/gen.py", line 278, in __getitem__
    return self.data[self.key(k)][1]
KeyError: 'gl'
```

This seems to be failing on the permissions check, because the manual `irc.state.nickToHostmask` lookup doesn't work across different networks if the caller is using a different nick.

**Comment by GLolol** [comment]
Oh, duplicate of #1233.

**Comment by ProgVal** [comment]
:’)
