### ISSUE TITLE
!google error

### ISSUE THREAD

**Issue by Taxick** [ProgVal/Limnoria#1282]
Hi.

When I try to use "!google test", I get this error: 

_(16:43:04) (@ Bobby) Taxick: An error has occurred and has been logged. Please contact this bot's administrator for more information._

And this error in the console..:

> ERROR 2017-02-06T17:45:54 Uncaught exception in ['google'].
> Traceback (most recent call last):
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/utils/web.py", line 146, in getUrlFd
>     fd = urlopen(request, timeout=timeout)
>   File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.5/urllib/request.py", line 472, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.5/urllib/request.py", line 504, in error
>     result = self._call_chain(*args)
>   File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/lib/python3.5/urllib/request.py", line 472, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.5/urllib/request.py", line 510, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 503: Service Unavailable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/callbacks.py", line 1305, in _callCommand
>     self.callCommand(command, irc, msg, *args, **kwargs)
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/utils/python.py", line 90, in g
>     f(self, *args, **kwargs)
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/callbacks.py", line 1282, in callCommand
>     method(irc, msg, *args, **kwargs)
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/commands.py", line 1082, in newf
>     f(self, irc, msg, args, *state.args, **state.kwargs)
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/plugins/Google/plugin.py", line 198, in google
>     data = self.search(text, msg.args[0], dict(optlist))
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/plugins/Google/plugin.py", line 134, in search
>     headers=headers).decode('utf8')
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/utils/web.py", line 192, in getUrl
>     return getUrlContent(*args, **kwargs)
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/utils/web.py", line 187, in getUrlContent
>     (target, text) = getUrlTargetAndContent(*args, **kwargs)
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/utils/web.py", line 169, in getUrlTargetAndContent
>     fd = getUrlFd(url, headers=headers, data=data, timeout=timeout)
>   File "/home/ircd/.local/lib/python3.5/site-packages/supybot/utils/web.py", line 151, in getUrlFd
>     raise Error(strError(e))
> supybot.utils.web.Error: HTTP Error 503: Service Unavailable
> ERROR 2017-02-06T17:45:54 Exception id: 0xdc450

I'm running ubuntu 16.10. and "python -V" give me this: "Python 2.7.12+", but I also have python3 installed. 

I have used: 

"**python3 -m pip install -r https://raw.githubusercontent.com/ProgVal/Limnoria/master/requirements.txt --user --upgrade**"

and

"**python3 -m pip install limnoria --user --upgrade**" to install the bot

I hope you can help me out here...

Regards

Taxick

**Comment by Taxick** [comment]
And I have a bonus question. Where can I find a complete list of commands the bot can use??

**Comment by ProgVal** [comment]
It's an error from Google, which probably detected you are using a bot. So there is nothing you can do, except use an other search plugin (eg. using Duckduckgo).

**Comment by ProgVal** [comment]
> Where can I find a complete list of commands the bot can use??

Do you mean a list of commands provided by the bot that your can use?

Use `@list` to list plugins, and `@list PluginName` to list commands in a plugin.
