### ISSUE TITLE
ipaddress module with python2 requires unicode instead of str

### ISSUE THREAD

**Issue by ddan39** [ProgVal/Limnoria#1342]
Based on the comment at the top of the drivers/Socket.py file, you are only expecting this module to be available with python 3.3+, but my system has a back-ported python2 version of the module installed. The below error is produced since the address is represented as a normal string instead of unicode string(which it would be by default in python3). Seems kind of silly that the ipaddress module requires unicode objects instead of regular python2 strings, but o well..

```
INFO 2018-07-09T02:59:22 Connecting to MyNetwork:6667.                                                                                                                 
ERROR 2018-07-09T02:59:22 Exception connecting to SAE:                                                                                                                            
Traceback (most recent call last):                                                                                                                                                
  File "/home/user/.local/lib/python2.7/site-packages/supybot/plugins/Owner/plugin.py", line 126, in __init__                                                                     
    self._connect(network)                                                                                                                                                        
  File "/home/user/.local/lib/python2.7/site-packages/supybot/plugins/Owner/plugin.py", line 163, in _connect                                                                     
    driver = drivers.newDriver(newIrc)                                                                                                                                            
  File "/home/user/.local/lib/python2.7/site-packages/supybot/drivers/__init__.py", line 190, in newDriver                                                                        
    driver = driverModule.Driver(irc)                                                                                                                                             
  File "/home/user/.local/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 90, in __init__                                                                            
    self.connect()                                                                                                                                                                
  File "/home/ser/.local/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 223, in connect                                                                            
    self.reconnect(reset=False, **kwargs)
  File "/home/ser/.local/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 289, in reconnect
    (ipaddress is None or not ipaddress.ip_address(address).is_loopback):
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 163, in ip_address
    ' a unicode object?' % address)
AddressValueError: '104.203.NN.NN' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?                          
ERROR 2018-07-09T02:59:22 Exception id: 0xfc5d1
ERROR 2018-07-09T02:59:22 Could not connect to MyNetwork: '104.203.NN.NN' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
```

**Comment by jlu5** [comment]
Can you see if this patch fixes the issue?

```patch
diff --git a/src/drivers/Socket.py b/src/drivers/Socket.py
index 40dbc297..c9e9d19f 100644
--- a/src/drivers/Socket.py
+++ b/src/drivers/Socket.py
@@ -39,9 +39,10 @@ import time
 import errno
 import select
 import socket
+import sys
 
 try:
-    import ipaddress
+    import ipaddress  # Python >= 3.3 or backported ipaddress
 except ImportError:
     # Python < 3.3
     ipaddress = None
@@ -284,9 +285,14 @@ class SocketDriver(drivers.IrcDriver, drivers.ServersMixin):
             self.conn.connect((address, port))
             if network_config.ssl():
                 self.starttls()
+
             # Suppress this warning for loopback IPs.
+            targetip = address
+            if sys.version_info[0] < 3:
+                # Backported Python 2 ipaddress demands unicode instead of str
+                targetip = targetip.decode('utf-8')
             elif (not network_config.requireStarttls()) and \
-                    (ipaddress is None or not ipaddress.ip_address(address).is_loopback):
+                    (ipaddress is None or not ipaddress.ip_address(targetip).is_loopback):
                 drivers.log.warning(('Connection to network %s '
                     'does not use SSL/TLS, which makes it vulnerable to '
                     'man-in-the-middle attacks and passive eavesdropping. '

```

**Comment by ddan39** [comment]
tested patch works with python 2.7 on debian stretch with the python-ipaddress package installed. thanks.
