### ISSUE TITLE
SedRegex raises 'not allowed to raise maximum limit'

### ISSUE THREAD

**Issue by traumschule** [ProgVal/Limnoria#1353]
The [line](/ProgVal/Limnoria/blob/master/src/commands.py#L112)
> resource.setrlimit(rsrc, (heap_size, heap_size))

on this gentoo raised
```
Process Process #5907 (for SedRegex.replacer):
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File ".local/lib64/python3.6/site-packages/supybot/callbacks.py", line 1090, in run
    self.__parent.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File ".local/lib64/python3.6/site-packages/supybot/commands.py", line 112, in newf
    resource.setrlimit(rsrc, (heap_size, heap_size))                             
ValueError: not allowed to raise maximum limit
```
For debugging i changed the code which fixed it:
```
    def newf(f, q, *args, **kwargs):
        if resource:
            rsrc = resource.RLIMIT_DATA
            try:
                resource.setrlimit(rsrc, (heap_size, heap_size))
            except Exception as e:
                log.error('Error: setrlimit failed. rsrc=%s heap_size=%s', rsrc, heap_size)
```
Logged output was:
> ERROR 2018-12-14T23:00:34 Error: setrlimit 2 -1

**Comment by traumschule** [comment]
With
```
            rsrc = resource.RLIMIT_DATA   
            (soft, hard) = resource.getrlimit()
            soft = min(soft, heap_size)
            hard = min(hard, heap_size)
            resource.setrlimit(rsrc, (soft, hard))
```
and
```
           (soft, hard) = resource.getrlimit()
            if soft == resource.RLIM_INFINITY:
                soft = heap_size
            else:
                soft = min(soft, heap_size)
            if hard == resource.RLIM_INFINITY:
                hard = heap_size
            else:
                hard = min(hard, heap_size)
            resource.setrlimit(rsrc, (soft, hard))
```
i get messages like
> Error: Search not found in the last 252 messages.

and
```
Process Process #4 (for SedRegex.replacer):
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File ".local/lib64/python3.6/site-packages/supybot/callbacks.py", line 1090, in run
    self.__parent.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File ".local/lib64/python3.6/site-packages/supybot/commands.py", line 112, in newf
    (soft, hard) = resource.getrlimit()
TypeError: getrlimit() takes exactly 1 argument (0 given)
```

**Comment by ProgVal** [comment]
Sorry, I meant this:

```diff
diff --git a/src/commands.py b/src/commands.py
index 0582bf7b..91e482fc 100644
--- a/src/commands.py
+++ b/src/commands.py
@@ -109,7 +109,16 @@ def process(f, *args, **kwargs):
     def newf(f, q, *args, **kwargs):
         if resource:
             rsrc = resource.RLIMIT_DATA
-            resource.setrlimit(rsrc, (heap_size, heap_size))
+            (soft, hard) = resource.getrlimit(rsrc)
+            if soft == resource.RLIM_INFINITY:
+                soft = heap_size
+            else:
+                soft = min(soft, heap_size)
+            if hard == resource.RLIM_INFINITY:
+                hard = heap_size
+            else:
+                hard = min(hard, heap_size)
+            resource.setrlimit(rsrc, (soft, hard))
         try:
             r = f(*args, **kwargs)
             q.put(r)
```

**Comment by traumschule** [comment]
This again gives
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File ".local/lib64/python3.6/site-packages/supybot/callbacks.py", line 1090, in run
    self.__parent.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File ".local/lib64/python3.6/site-packages/supybot/commands.py", line 121, in newf
    resource.setrlimit(rsrc, (soft, hard))
ValueError: not allowed to raise maximum limit
```
So i'm going with
```
            (soft, hard) = resource.getrlimit(rsrc)
            if soft == resource.RLIM_INFINITY:
                soft = heap_size
            else:
                soft = min(soft, heap_size)
            if hard == resource.RLIM_INFINITY:
                hard = heap_size
            else:
                hard = min(hard, heap_size)
            try:
                resource.setrlimit(rsrc, (soft, hard))
            except Exception as e:
                log.error('Error: setrlimit failed. rsrc=%s soft=%s hard=%s', rsrc, soft, hard)
        try:
```
which gives an error but works:
> ERROR 2018-12-14T23:51:01 Error: setrlimit failed. rsrc=2 soft=-1 hard=-1

**Comment by ProgVal** [comment]
How about this one?

```diff
diff --git a/src/commands.py b/src/commands.py
index 0582bf7b..0798b9ad 100644
--- a/src/commands.py
+++ b/src/commands.py
@@ -109,7 +109,16 @@ def process(f, *args, **kwargs):
     def newf(f, q, *args, **kwargs):
         if resource:
             rsrc = resource.RLIMIT_DATA
-            resource.setrlimit(rsrc, (heap_size, heap_size))
+            (soft, hard) = resource.getrlimit(rsrc)
+            if soft == resource.RLIM_INFINITY:
+                soft = heap_size
+            elif heap_size != resource.RLIM_INFINITY:
+                soft = min(soft, heap_size)
+            if hard == resource.RLIM_INFINITY:
+                hard = heap_size
+            elif heap_size != resource.RLIM_INFINITY:
+                hard = min(hard, heap_size)
+            resource.setrlimit(rsrc, (soft, hard))
         try:
             r = f(*args, **kwargs)
             q.put(r)
```

**Comment by traumschule** [comment]
No error this time.

**Comment by ProgVal** [comment]
Great, thanks for your help!
