### ISSUE TITLE
Scheduler.* tests timing out

### ISSUE THREAD

**Issue by mapreri** [ProgVal/Limnoria#1385]
Hi,

We are seeing some tests timing out:

```
======================================================================
FAIL: testAddRemove (Scheduler.test.SchedulerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_limnoria/build/supybot/test.py", line 212, in runTest
    originalRunTest()
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_limnoria/build/supybot/plugins/Scheduler/test.py", line 46, in testAddRemove
    self.assertResponse(' ', 'testAddRemove')
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_limnoria/build/supybot/test.py", line 386, in assertResponse
    raise TimeoutError(query)
supybot.test.TimeoutError: ' ' timed out

======================================================================
FAIL: testRepeat (Scheduler.test.SchedulerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_limnoria/build/supybot/test.py", line 212, in runTest
    originalRunTest()
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_limnoria/build/supybot/plugins/Scheduler/test.py", line 73, in testRepeat
    self.assertResponse(' ', 'testRepeat')
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_limnoria/build/supybot/test.py", line 386, in assertResponse
    raise TimeoutError(query)
supybot.test.TimeoutError: ' ' timed out

======================================================================
FAIL: testRepeatWorksWithNestedCommands (Scheduler.test.SchedulerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_limnoria/build/supybot/test.py", line 212, in runTest
    originalRunTest()
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_limnoria/build/supybot/plugins/Scheduler/test.py", line 83, in testRepeatWorksWithNestedCommands
    self.assertResponse(' ', 'foo nested')
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_limnoria/build/supybot/test.py", line 386, in assertResponse
    raise TimeoutError(query)
supybot.test.TimeoutError: ' ' timed out

----------------------------------------------------------------------
Ran 892 tests in 265.608s

FAILED (failures=3, skipped=14)
```

I also notice that you are excluding those tests in trevis CI (toghether with the Filter plugin's, even if they don't cause me any issue, so you may as consider re-enabling those, it was disabled back in 2013 apparently), but I think it should be properly fixed instead :)

**Comment by ProgVal** [comment]
I have real trouble reproducing this on my computer :/

**Comment by mapreri** [comment]
it's really the same for me, I could never hit it by myself :(

**Comment by ProgVal** [comment]
I can now reproduce it with `supybot-test -v --no-network --disable-multiprocessing test Scheduler`. It fails iff `test` tests are run before `Scheduler` tests.

**Comment by ProgVal** [comment]
got it

**Comment by mapreri** [comment]
Oh, wow.  That must have been tricky to track down!

Thanks for chasing after this, I'll pick the 3 commits and confirm it works for me everywhere :)

**Comment by ProgVal** [comment]
Only b2f6c3c83fe2c460dd17978d9d1b378e17baf448 is needed
