### ISSUE TITLE
generating docs fails for plugins like "alias"

### ISSUE THREAD

**Issue by ghost** [ProgVal/Limnoria#1388]
~/.local/bin/supybot-plugin-doc Alias:

```
Generating documentation for Alias...
Traceback (most recent call last):
  File "/home/limnoria/.local/bin/supybot-plugin-doc", line 297, in <module>
    genDoc(Plugin, options)
  File "/home/limnoria/.local/bin/supybot-plugin-doc", line 242, in genDoc
    fd.write(f())
  File "/home/limnoria/.local/bin/supybot-plugin-doc", line 196, in renderSTX
    for confValues in self.genConfig(confs, 2):
  File "/home/limnoria/.local/bin/supybot-plugin-doc", line 213, in genConfig
    if isinstance(v._default, basestring) or v._default is None:
  File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/registry.py", line 236, in __getattr__
    (self.__class__.__name__, attr))
AttributeError: Group has no attribute _default
```

**Comment by jlu5** [comment]
Hi,

It seems this piece of code has fallen through the cracks and broke with some recent changes. May I ask what you're using it for, out of curiosity?

**Comment by sfsoc** [comment]
Thanks for the tag and the reply.

My plan was to build a little database where I don't need to care about building a front-end and back-end. It's no serious business more games. So I was testing earlier releases and the one from 8th September works.

**Comment by sfsoc** [comment]
Correction: in the older version alias works but other interesting modules like factoids and aka don't work. Would it make sense to go and try to read the source?
