### ISSUE TITLE
Aka plugin tests for webui run when --no-network is selected

### ISSUE THREAD

**Issue by NP-Hardass** [ProgVal/Limnoria#1392]
Aka plugin tests for webui run when --no-network is selected
I think this is in error.

```
ERROR: testToggleWebEnable (Aka.test.AkaWebUITestCase)                                                    [4180/19447]
----------------------------------------------------------------------                                                
Traceback (most recent call last):                                                                                    
  File "/var/tmp/portage/net-irc/limnoria-20191123/work/Limnoria-master-2019-11-23-python2_7/build/lib/supybot/plugins/Aka/test.py", line 305, in setUp                                                                                     
    httpserver.startServer()                                                                                          
  File "/var/tmp/portage/net-irc/limnoria-20191123/work/Limnoria-master-2019-11-23-python2_7/build/lib/supybot/httpserver.py", line 443, in startServer                                                                                     
    server = SupyHTTPServer(address, protocol, SupyHTTPRequestHandler)                                                
  File "/var/tmp/portage/net-irc/limnoria-20191123/work/Limnoria-master-2019-11-23-python2_7/build/lib/supybot/httpserver.py", line 180, in __init__                                                                                        
    HTTPServer.__init__(self, address, callback)                                                                      
  File "/usr/lib64/python2.7/SocketServer.py", line 417, in __init__                                                  
    self.server_bind()                                                                                                
  File "/var/tmp/portage/net-irc/limnoria-20191123/work/Limnoria-master-2019-11-23-python2_7/build/lib/supybot/httpserver.py", line 187, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

Are you able to confirm?

**Comment by ProgVal** [comment]
`--no-network` means the tests won't send any network request. But it's a bug that the tests require port 8080 to be free, instead of selecting a random free port.
