### ISSUE TITLE
Add tor support && Add suport for socks proxy

### ISSUE THREAD

**Issue by Juliaria08** [ProgVal/Limnoria#1444]
# Support for making one or more nets be a tor hidden service
Having a config setting like ```@config networks.network.tor true```,  and you set the network  address to be the onion link, also that supports ssl over tor ( that is not needed but some nets are misconfigured ) and non ssl  conn over tor and it also supports connecting over tor one or more networks that dont have tor address

**Comment by ProgVal** [comment]
Hi, it should already be possible by setting up a SOCKS proxy for Tor; then setting its URL in in `supybot.networks.<network>.socksproxy`

**Comment by Juliaria08** [comment]
Ok

**Comment by Juliaria08** [comment]
Nop it does not work

**Comment by Juliaria08** [comment]
```
Traceback (most recent call last):
    1   File "/usr/local/lib/python3.8/dist-packages/socks.py", line 809, in connect
    2     negotiate(self, dest_addr, dest_port)
    3   File "/usr/local/lib/python3.8/dist-packages/socks.py", line 443, in _negotiate_SOCKS5
    4     self.proxy_peername, self.proxy_sockname = self._SOCKS5_request(
    5   File "/usr/local/lib/python3.8/dist-packages/socks.py", line 533, in _SOCKS5_request
    6     raise SOCKS5Error("{:#04x}: {}".format(status, error))
    7 socks.SOCKS5Error: 0x01: General SOCKS server failure
    8 
    9 During handling of the above exception, another exception occurred:
   10 
   11 Traceback (most recent call last):
   12   File "/usr/local/lib/python3.8/dist-packages/supybot/drivers/Socket.py", line 300, in reconnect
   13     self.conn.connect(
   14   File "/usr/local/lib/python3.8/dist-packages/socks.py", line 47, in wrapper
   15     return function(*args, **kwargs)
   16   File "/usr/local/lib/python3.8/dist-packages/socks.py", line 814, in connect
   17     raise GeneralProxyError("Socket error", error)
   18 socks.GeneralProxyError: Socket error: 0x01: General SOCKS server failure
   19 
   20 During handling of the above exception, another exception occurred:
   21 
   22 Traceback (most recent call last):
   23   File "/usr/local/lib/python3.8/dist-packages/supybot/drivers/__init__.py", line 149, in run
   24     driver.run()
   25   File "/usr/local/lib/python3.8/dist-packages/supybot/drivers/Socket.py", line 186, in run
   26     self.reconnect()
   27   File "/usr/local/lib/python3.8/dist-packages/supybot/drivers/Socket.py", line 326, in reconnect
   28     if e.args[0] == 115:
```

**Comment by ProgVal** [comment]
It means your SOCKS server doesn't work, or the URL you used is incorrect

**Comment by Juliaria08** [comment]
The url is the tor default 127.0.0.1:9050

**Comment by Juliaria08** [comment]
```
  7 2021-02-07T08:27:53  <julian> .config networks.testnetnav.nick test
  6 2021-02-07T08:27:53  <boty> julian: The operation succeeded.
  5 2021-02-07T08:28:18  <julian> .config networks.testnetnav.socksproxy
  4 2021-02-07T08:28:18  <boty> julian: 127.0.0.1:9050
  3 2021-02-07T08:29:16  <julian> .config networks.testnetnav.socksproxy
  2 2021-02-07T08:29:16  <boty> julian: 127.0.0.1:9050
  1 2021-02-07T08:29:26  <julian> .config networks.testnetnav.socksproxy 127.0.0.1:9050
69  2021-02-07T08:29:26  <boty> julian: The operation succeeded.
```

**Comment by ProgVal** [comment]
Could you paste the entire error log? (the one above is missing the end)

**Comment by Juliaria08** [comment]
https://envs.sh/nu.log

**Comment by ProgVal** [comment]
It looks like you're connecting it to something that isn't a SOCKS5 server.

Could you try with an other SOCKS client that isn't Limnoria?

**Comment by Juliaria08** [comment]
It is with torsocks works

**Comment by ProgVal** [comment]
Then I don't know; try asking PySocks here: https://github.com/Anorov/PySocks

**Comment by Juliaria08** [comment]
Ok
