### ISSUE TITLE
Errors when `!user@host` missing from message prefixes (eg. when used by RELAYMSG'd user)

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1451]
Channel:

```
021-136 18:43:42 EEST <M1kaela/T> <ddg search supybot
2021-136 18:43:43 EEST <%R-66Y> Supybot download | SourceForge.net - Nested commands, easy configuration, and an incredibly flexible and easy-to-use plugin system distinguish Supybot from other IRC bots. There simply isn't a more flexible or easier to use IRC bot! <https://sourceforge.net/projects/supybot/>, GitHub - Supybot/Supybot - Supybot was maintained. For years, there have been idle threats of that happening again, but it has not come to pass. Instead, 
2021-136 18:43:44 EEST <%R-66Y> various friendly forks were created, with [Limnoria] (https://github.com/ProgVal/Limnoria) seeming to have the most momentum. <https://github.com/Supybot/Supybot>, supybot · PyPI - A robust, full-featured Python IRC bot with a clean and flexible plugin API. Equipped with a complete ACL system for specifying user permissions with as much as per-command granularity. Batteries are included in the form of numerous plugins already written.  (1 more message)
2021-136 18:43:46 EEST <%R-66Y> Error: IndexError: list index out of range
2021-136 18:43:49 EEST <M1kaela/T> <more
2021-136 18:43:49 EEST <%R-66Y> Error: IndexError: list index out of range
```

`M1kaela/T` is a Telegram user through RELAYMSG, `supybot.reply.mores.instant` is set to 2.

> The current (running) version of this Limnoria is 2021.04.11, running on Python 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]. The newest versions available online are 2021.04.11 (in master), 2021.05.07 (in testing).

I am using Debian 10 on the VPS, this doesn't happen when a normal IRC user uses the command.

Log:

```python3
May 16 18:43:42 etro supybot[11231]: INFO 2021-05-16T15:43:42 ddg search called on #test by "M1kaela/T".                                                                                    
May 16 18:43:42 etro supybot[11231]: ERROR 2021-05-16T15:43:42 Error while sending reply
May 16 18:43:42 etro supybot[11231]: Traceback (most recent call last):
May 16 18:43:42 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/callbacks.py", line 959, in reply                                                    
May 16 18:43:42 etro supybot[11231]:     sendImmediately=sendImmediately, stripCtcp=stripCtcp)                                                                                              
May 16 18:43:42 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/callbacks.py", line 1145, in _sendReply                                              
May 16 18:43:42 etro supybot[11231]:     mask = prefix.split('!', 1)[1]
May 16 18:43:42 etro supybot[11231]: IndexError: list index out of range
May 16 18:43:42 etro supybot[11231]: ERROR 2021-05-16T15:43:42 Exception id: 0x24751
May 16 18:43:42 etro supybot[11231]: ERROR 2021-05-16T15:43:42 Uncaught exception in ['ddg', 'search'].                                                                                     
May 16 18:43:42 etro supybot[11231]: Traceback (most recent call last):
May 16 18:43:42 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/callbacks.py", line 1552, in _callCommand                                            
May 16 18:43:42 etro supybot[11231]:     self.callCommand(command, irc, msg, *args, **kwargs)
May 16 18:43:42 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/utils/python.py", line 90, in g                                                      
May 16 18:43:42 etro supybot[11231]:     f(self, *args, **kwargs)
May 16 18:43:42 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/callbacks.py", line 1518, in callCommand                                             
May 16 18:43:42 etro supybot[11231]:     method(irc, msg, *args, **kwargs)
May 16 18:43:42 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/commands.py", line 1116, in newf                                                     
May 16 18:43:42 etro supybot[11231]:     f(self, irc, msg, args, *state.args, **state.kwargs)
May 16 18:43:42 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/plugins/DDG/plugin.py", line 165, in search                                          
May 16 18:43:42 etro supybot[11231]:     irc.reply(', '.join(strings))
May 16 18:43:42 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/callbacks.py", line 959, in reply                                                    
May 16 18:43:42 etro supybot[11231]:     sendImmediately=sendImmediately, stripCtcp=stripCtcp)                                                                                              
May 16 18:43:42 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/callbacks.py", line 1145, in _sendReply                                              
May 16 18:43:42 etro supybot[11231]:     mask = prefix.split('!', 1)[1]
May 16 18:43:42 etro supybot[11231]: IndexError: list index out of range
May 16 18:43:42 etro supybot[11231]: ERROR 2021-05-16T15:43:42 Exception id: 0xad451
May 16 18:43:49 etro supybot[11231]: INFO 2021-05-16T15:43:49 more called on #test by "M1kaela/T".                                                                                          
May 16 18:43:49 etro supybot[11231]: ERROR 2021-05-16T15:43:49 Uncaught exception in ['more'].                                                                                              
May 16 18:43:49 etro supybot[11231]: Traceback (most recent call last):
May 16 18:43:49 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/callbacks.py", line 1552, in _callCommand                                            
May 16 18:43:49 etro supybot[11231]:     self.callCommand(command, irc, msg, *args, **kwargs)
May 16 18:43:49 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/utils/python.py", line 90, in g                                                      
May 16 18:43:49 etro supybot[11231]:     f(self, *args, **kwargs)
May 16 18:43:49 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/callbacks.py", line 1518, in callCommand                                             
May 16 18:43:49 etro supybot[11231]:     method(irc, msg, *args, **kwargs)
May 16 18:43:49 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/commands.py", line 1116, in newf                                                     
May 16 18:43:49 etro supybot[11231]:     f(self, irc, msg, args, *state.args, **state.kwargs)
May 16 18:43:49 etro supybot[11231]:   File "/home/limnoria/.local/lib/python3.7/site-packages/supybot/plugins/Misc/plugin.py", line 384, in more                                           
May 16 18:43:49 etro supybot[11231]:     userHostmask = msg.prefix.split('!', 1)[1]
May 16 18:43:49 etro supybot[11231]: IndexError: list index out of range
May 16 18:43:49 etro supybot[11231]: ERROR 2021-05-16T15:43:49 Exception id: 0x7be01
```

**Comment by ProgVal** [comment]
Hi,

You're going to get this on most plugins; many parts of Limnoria assume message prefixes are `nick!user@host`, not just `nick`; so fixing this is not trivial.

FWIW I am aware this is not guaranteed by the RFCs, but I don't know any server that sends prefixes without user and host, so this was also not a priority so far.
