### ISSUE TITLE
RSS feature request: Show author/creator names

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1471]
I am missing how BitBot was showing names of people who wrote the articles, they seem to be either in `<author>` or `<dc:creator>` tags.

* https://www.rssboard.org/rss-profile#element-channel-item-author
* https://www.rssboard.org/rss-profile#namespace-elements-dublin-creator

**Comment by ProgVal** [comment]
You should be abl to use `$author` in `plugins.RSS.format` or `plugins.RSS.announceFormat`

**Comment by Mikaela** [comment]
Thanks, `$author` seems to be undocumented in the config helps. However specifying it breaks feeds that don't have author information.

```
2021-157 20:41:38 EEST <~Mikaela> /crtshmikaelainfo
2021-157 20:41:39 EEST <@R-66Y> Error: KeyError: 'author'
```

```python3
Jun 06 20:41:38 etro supybot[308332]: INFO 2021-06-06T20:41:38 crtshmikaelainfo called on #test by "Mikaela!~u@mikaela.info".
Jun 06 20:41:38 etro supybot[308332]: ERROR 2021-06-06T20:41:38 Uncaught exception in ['crtshmikaelainfo'].
Jun 06 20:41:38 etro supybot[308332]: Traceback (most recent call last):
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/callbacks.py", line 1574, in _callCommand
Jun 06 20:41:38 etro supybot[308332]:     self.callCommand(command, irc, msg, *args, **kwargs)
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/utils/python.py", line 90, in g
Jun 06 20:41:38 etro supybot[308332]:     f(self, *args, **kwargs)
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/callbacks.py", line 1540, in callCommand
Jun 06 20:41:38 etro supybot[308332]:     method(irc, msg, *args, **kwargs)
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/plugins/RSS/plugin.py", line 149, in f
Jun 06 20:41:38 etro supybot[308332]:     self2.rss(irc, msg, args)
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/commands.py", line 1116, in newf
Jun 06 20:41:38 etro supybot[308332]:     f(self, irc, msg, args, *state.args, **state.kwargs)
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/plugins/RSS/plugin.py", line 669, in rss
Jun 06 20:41:38 etro supybot[308332]:     irc.replies(headlines, joiner=sep)
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/callbacks.py", line 1254, in replies
Jun 06 20:41:38 etro supybot[308332]:     return super(NestedCommandsIrcProxy, self).replies(L,
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/callbacks.py", line 539, in replies
Jun 06 20:41:38 etro supybot[308332]:     return self.reply(prefixer(joiner(L)), **kwargs)
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/plugins/RSS/plugin.py", line 666, in <lambda>
Jun 06 20:41:38 etro supybot[308332]:     headlines = map(lambda e:self.format_entry(irc.network, channel, feed, e, False),
Jun 06 20:41:38 etro supybot[308332]:   File "/home/limnoria/.local/lib/python3.9/site-packages/supybot/plugins/RSS/plugin.py", line 485, in format_entry
Jun 06 20:41:38 etro supybot[308332]:     s = string.Template(template).substitute(
Jun 06 20:41:38 etro supybot[308332]:   File "/usr/lib/python3.9/string.py", line 121, in substitute
Jun 06 20:41:38 etro supybot[308332]:     return self.pattern.sub(convert, self.template)
Jun 06 20:41:38 etro supybot[308332]:   File "/usr/lib/python3.9/string.py", line 114, in convert
Jun 06 20:41:38 etro supybot[308332]:     return str(mapping[named])
Jun 06 20:41:38 etro supybot[308332]:   File "/usr/lib/python3.9/collections/__init__.py", line 941, in __getitem__
Jun 06 20:41:38 etro supybot[308332]:     return self.__missing__(key)            # support subclasses that define __missing__
Jun 06 20:41:38 etro supybot[308332]:   File "/usr/lib/python3.9/collections/__init__.py", line 933, in __missing__
Jun 06 20:41:38 etro supybot[308332]:     raise KeyError(key)
Jun 06 20:41:38 etro supybot[308332]: KeyError: 'author'
Jun 06 20:41:38 etro supybot[308332]: ERROR 2021-06-06T20:41:38 Exception id: 0xafd8b

```
