### ISSUE TITLE
Remove shadowing of any()

### ISSUE THREAD

**Issue by jlu5** [progval/Limnoria#1534]
For legacy reasons, Limnoria includes [its own definition of `any()`](https://github.com/progval/Limnoria/blob/fccb4f705bb5ead64059a1f5994ef5e593095062/src/commands.py#L959) which clash with the Python builtins. This is pretty confusing at times because we do `from supybot.commands import *`

Worse, the Supybot version has completely different semantics so expected uses of the builtin just throw non-descriptive errors:

```
>>> supybot.commands.any([0,''])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/limnoria-2023.4.27-py3.9.egg/supybot/commands.py", line 962, in __init__
    self.__parent.__init__(spec)
  File "/usr/local/lib/python3.9/dist-packages/limnoria-2023.4.27-py3.9.egg/supybot/commands.py", line 906, in __init__
    assert isinstance(spec, context)
AssertionError
```

Because `supybot.commands.any` takes a `context` and the builtin takes an iterable, it should be easy to route between the two different uses. So my idea for cleaning this up would be as follows:

1. Rename `supybot.commands.any` to `supybot.commands.anyArguments` (or whatever name is suggested)
2. Replace `supybot.commands.any` with a new definition that instantiates/calls `supybot.commands.any` if given a context (but raises a deprecation warning), and otherwise passes on the call to the builtins version
3. (Eventually) remove the old `supybot.commands.any` link

**Comment by progval** [comment]
Also affects:

* `format` defined in `supybot.utils.str` and reexported by `supybot.commands`
* `all` defined in `supybot.utils.iter`

> Because supybot.commands.any takes a context and the builtin takes an iterable

the main use is to make the former take a single string
