### ISSUE TITLE
`setValue` is no longer called before `__str__` on registry values

### ISSUE THREAD

**Issue by progval** [progval/Limnoria#1604]
causing this error:

```
ERROR 2024-12-01T20:52:03 Exception printing default value of supybot.plugins.ChannelStats.frowns:
Traceback (most recent call last):
  File "/home/dev-irc/Limnoria/src/registry.py", line 161, in close
    lines.append('# Default value: %s\n' % x)
                 ~~~~~~~~~~~~~~~~~~~~~~~~^~~
  File "/home/dev-irc/Limnoria/src/plugins/ChannelStats/config.py", line 58, in __str__
    return self.s
           ^^^^^^
  File "/home/dev-irc/Limnoria/src/registry.py", line 243, in __getattr__
    self.__nonExistentEntry(attr)
  File "/home/dev-irc/Limnoria/src/registry.py", line 225, in __nonExistentEntry
    raise NonExistentRegistryEntry(s)
supybot.registry.NonExistentRegistryEntry: 's' is not a valid entry in 'unset'
```

this is a regression from #1601.

ChannelStats could easily be adapted to work with this, but I consider this to be a (minor) API breakage, which may affect other plugins. I do not see a way to fix this without re-breaking #1349, which is not worth it.

@BlankEclair any idea?

**Comment by BlankEclair** [comment]
The ideal answer is to edit the plugin to make it use one value, such as 
Regexp in 
https://github.com/progval/Limnoria/blob/master/src/registry.py#L775

The workaround I have in mind is not very elegant, but perhaps if an 
exception is thrown while stringifying it, we call setValue and try again

**Comment by progval** [comment]
> The ideal answer is to edit the plugin to make it use one value, such as
> Regexp in
> https://github.com/progval/Limnoria/blob/master/src/registry.py#L775

After some thoughts, I'll go with that. It doesn't really make sense for `__str__` to have load-bearing side-effect and expect it to be called in this kind of situation.
