### ISSUE TITLE
Dict plugin, python 2.x Unicode decode error

### ISSUE THREAD

**Issue by kytvi2p** [ProgVal/Limnoria#510]
```
ERROR 2013-08-25T16:21:47 Uncaught exception in ['dict'].
Traceback (most recent call last):
  File "/home/kytv/relay/lib/python2.7/site-packages/limnoria-2013_08_25T14_25_12_0000-py2.7.egg/supybot/callbacks.py", line 1265, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/home/kytv/relay/lib/python2.7/site-packages/limnoria-2013_08_25T14_25_12_0000-py2.7.egg/supybot/utils/python.py", line 86, in g
    f(self, *args, **kwargs)
  File "/home/kytv/relay/lib/python2.7/site-packages/limnoria-2013_08_25T14_25_12_0000-py2.7.egg/supybot/callbacks.py", line 1246, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/home/kytv/relay/lib/python2.7/site-packages/limnoria-2013_08_25T14_25_12_0000-py2.7.egg/supybot/commands.py", line 1073, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/kytv/relay/lib/python2.7/site-packages/limnoria-2013_08_25T14_25_12_0000-py2.7.egg/supybot/plugins/Dict/plugin.py", line 124, in dict
    s = format(_('%L responded: %s'), list(dbs), '; '.join(L))
  File "/home/kytv/relay/lib/python2.7/site-packages/limnoria-2013_08_25T14_25_12_0000-py2.7.egg/supybot/utils/str.py", line 532, in format
    return _formatRe.sub(sub, s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 20: ordinal not in range(128)
ERROR 2013-08-25T16:21:47 Exception id: 0x2253c
```

This is not a problem with Python 3.3.

**Comment by jlu5** [comment]
Closing, as Limnoria now requires Python 3.
