### ISSUE TITLE
Bot fails to reconnect after netsplit. Python error.

### ISSUE THREAD

**Issue by slackhead** [ProgVal/Limnoria#518]
After netsplits on freenode the bot fails to reconnect. This is from the log:

INFO 2013-09-27T08:28:21 supybot Reconnecting to freenode.
INFO 2013-09-27T08:28:21 supybot Sending PASS command, not logging the password.
ERROR 2013-09-27T08:29:01 supybot Uncaught exception in Irc.takeMsg:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/supybot/log.py", line 355, in m
    return f(self, _args, *_kwargs)
  File "/usr/lib64/python2.7/site-packages/supybot/irclib.py", line 762, in takeMsg
    self.driver.reconnect()
  File "/usr/lib64/python2.7/site-packages/supybot/drivers/Socket.py", line 268, in reconnect
    attempt=self._attempt)
  File "/usr/lib64/python2.7/site-packages/supybot/utils/net.py", line 84, in getAddressFromHostn
ame
    addrinfo = socket.getaddrinfo(host, None)
error: [Errno 110] Connection timed out
ERROR 2013-09-27T08:29:01 supybot Exception id: 0xa050b
INFO 2013-09-27T08:58:31 supybot Flushers flushed and garbage collected.

The last INFO line is repeated infinitely until I restart the bot.

**Comment by GLolol** [comment]
I think this is the same issue as #513.
