### ISSUE TITLE
ShrinkUrl: ln and goo are broken. xrl is blocking me.

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#618]
xrl:

```
'Error:  Blocked - github.com in multi.uribl.com (127.0.0.1 -> Query Refused. See http://uribl.com/refused.shtml for more information [Your DNS IP: 207.171.7.218])\n'
```
goo:

```pytb
CRITICAL 2014-05-09T14:42:33 supybot goo
INFO 2014-05-09T14:42:39 supybot goo called on ##Mkaysi by "Mikaela!mkaysi@unaffiliated/mikaela".
INFO 2014-05-09T14:42:39 supybot goo called on ##Mkaysi by "Mikaela!mkaysi@unaffiliated/mikaela".
ERROR 2014-05-09T14:42:39 supybot Shrinking URL failed. Trying again.
Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 382, in __getitem__
    return self.adds[key]
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/618'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 257, in find
    return self.default
AttributeError: 'Reader' object has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 263, in _getGooUrl
    return self.db.get('goo', url)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 59, in get
    return self.dbs[service][url]
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 384, in __getitem__
    return self.cdb[key] # If this raises KeyError, we lack key.
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 259, in find
    raise KeyError(key)
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/618'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 81, in newf
    return f(*args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 268, in _getGooUrl
    text = utils.web.getUrl(self._gooApi, data=data, headers=headers)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/web.py", line 148, in getUrl
    fd = getUrlFd(url, headers=headers, data=data, timeout=timeout)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/web.py", line 126, in getUrlFd
    fd = urllib.request.urlopen(request, timeout=timeout)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 467, in open
    req = meth(req)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 1179, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
ERROR 2014-05-09T14:42:39 supybot Exception id: 0xcbdcf
ERROR 2014-05-09T14:42:40 supybot Shrinking URL failed. Trying again.
Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 382, in __getitem__
    return self.adds[key]
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/618'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 257, in find
    return self.default
AttributeError: 'Reader' object has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 263, in _getGooUrl
    return self.db.get('goo', url)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 59, in get
    return self.dbs[service][url]
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 384, in __getitem__
    return self.cdb[key] # If this raises KeyError, we lack key.
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 259, in find
    raise KeyError(key)
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/618'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 81, in newf
    return f(*args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 268, in _getGooUrl
    text = utils.web.getUrl(self._gooApi, data=data, headers=headers)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/web.py", line 148, in getUrl
    fd = getUrlFd(url, headers=headers, data=data, timeout=timeout)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/web.py", line 126, in getUrlFd
    fd = urllib.request.urlopen(request, timeout=timeout)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 467, in open
    req = meth(req)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 1179, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
ERROR 2014-05-09T14:42:40 supybot Exception id: 0xcbdcf
ERROR 2014-05-09T14:42:41 supybot Shrinking URL failed. Trying again.
Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 382, in __getitem__
    return self.adds[key]
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/618'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 257, in find
    return self.default
AttributeError: 'Reader' object has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 263, in _getGooUrl
    return self.db.get('goo', url)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 59, in get
    return self.db.get('goo', url)                                                                                                                                                       [48/1960]
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 59, in get
    return self.dbs[service][url]
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 384, in __getitem__
    return self.cdb[key] # If this raises KeyError, we lack key.
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 259, in find
    raise KeyError(key)
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/618'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 81, in newf
    return f(*args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 268, in _getGooUrl
    text = utils.web.getUrl(self._gooApi, data=data, headers=headers)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/web.py", line 148, in getUrl
    fd = getUrlFd(url, headers=headers, data=data, timeout=timeout)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/web.py", line 126, in getUrlFd
    fd = urllib.request.urlopen(request, timeout=timeout)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 467, in open
    req = meth(req)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 1179, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
ERROR 2014-05-09T14:42:41 supybot Exception id: 0xcbdcf
ERROR 2014-05-09T14:42:42 supybot Spec: [<context for url>]
ERROR 2014-05-09T14:42:42 supybot Received args: []
ERROR 2014-05-09T14:42:42 supybot Extra args: ['url']
ERROR 2014-05-09T14:42:42 supybot Uncaught exception in ['goo'].
Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 382, in __getitem__
    return self.adds[key]
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/618'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 257, in find
    return self.default
AttributeError: 'Reader' object has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 263, in _getGooUrl
    return self.db.get('goo', url)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 59, in get
    return self.db.get('goo', url)                                                                                                                                                        [0/1960]
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 59, in get
    return self.dbs[service][url]
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 384, in __getitem__
    return self.cdb[key] # If this raises KeyError, we lack key.
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 259, in find
    raise KeyError(key)
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/618'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/callbacks.py", line 1266, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 100, in callCommand
    self.__parent.callCommand(command, irc, msg, *args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/callbacks.py", line 1247, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/commands.py", line 69, in newf
    f(self, irc, msg, args, *L, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/commands.py", line 1076, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 282, in goo
    goourl = self._getGooUrl(url)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 85, in newf
    return f(*args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 268, in _getGooUrl
    text = utils.web.getUrl(self._gooApi, data=data, headers=headers)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/web.py", line 148, in getUrl
    fd = getUrlFd(url, headers=headers, data=data, timeout=timeout)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/utils/web.py", line 126, in getUrlFd
    fd = urllib.request.urlopen(request, timeout=timeout)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 467, in open
    req = meth(req)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/urllib/request.py", line 1179, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
ERROR 2014-05-09T14:42:42 supybot Exception id: 0x1f30b
INFO 2014-05-09T14:42:47 supybot logmark called on ##Mkaysi by "Mikaela!mkaysi@unaffiliated/mikaela".
CRITICAL 2014-05-09T14:42:47 supybot endgoo
```

ln:

```pytb
ERROR 2014-05-09T14:27:51 supybot Shrinking URL failed. Trying again.
Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 382, in __getitem__
    return self.adds[key]
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/616'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 257, in find
    return self.default
AttributeError: 'Reader' object has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 175, in _getLnUrl
    return self.db.get('ln', url)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 59, in get
    return self.dbs[service][url]
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 384, in __getitem__
    return self.cdb[key] # If this raises KeyError, we lack key.
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 259, in find
    raise KeyError(key)
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/616'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 81, in newf
    return f(*args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 185, in _getLnUrl
    raise ShrinkError(text)
ShrinkUrl.plugin.ShrinkError: Correct password (not []) is required to use this service to curb abuse.
ERROR 2014-05-09T14:27:51 supybot Exception id: 0x98770
ERROR 2014-05-09T14:27:53 supybot Shrinking URL failed. Trying again.
Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 382, in __getitem__
    return self.adds[key]
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/616'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 257, in find
    return self.default
AttributeError: 'Reader' object has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 175, in _getLnUrl
    return self.db.get('ln', url)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 59, in get
    return self.dbs[service][url]
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 384, in __getitem__
    return self.cdb[key] # If this raises KeyError, we lack key.
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 259, in find
    raise KeyError(key)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 259, in find                                                                                          [0/1806]
    raise KeyError(key)
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/616'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 81, in newf
    return f(*args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 185, in _getLnUrl
    raise ShrinkError(text)
ShrinkUrl.plugin.ShrinkError: Correct password (not []) is required to use this service to curb abuse.
ERROR 2014-05-09T14:27:53 supybot Exception id: 0x98770
ERROR 2014-05-09T14:27:54 supybot Shrinking URL failed. Trying again.
Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 382, in __getitem__
    return self.adds[key]
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/616'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 257, in find
    return self.default
AttributeError: 'Reader' object has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 175, in _getLnUrl
    return self.db.get('ln', url)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 59, in get
    return self.dbs[service][url]
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 384, in __getitem__
    return self.cdb[key] # If this raises KeyError, we lack key.
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/cdb.py", line 259, in find
    raise KeyError(key)
KeyError: 'https%3A//github.com/ProgVal/Limnoria/issues/616'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 81, in newf
    return f(*args, **kwargs)
  File "/home/users/mkaysi/.local/lib/python3.3/site-packages/supybot/plugins/ShrinkUrl/plugin.py", line 185, in _getLnUrl
    raise ShrinkError(text)
ShrinkUrl.plugin.ShrinkError: Correct password (not []) is required to use this service to curb abuse.
ERROR 2014-05-09T14:27:54 supybot Exception id: 0x98770
```

**Comment by GLolol** [comment]
`xrl` is removed in #1026, `ln` just seems completely broken at their end (503 error still). I'm thinking the latter should be removed as a whole.

`goo` works fine again.
