### ISSUE TITLE
UnicodeDecodeError with some Akas

### ISSUE THREAD

**Issue by Ban3** [ProgVal/Limnoria#649]
give is an aka alias:

```
.aka add give "echo $1, [$*]"
```

Giving something like 'list' works fine, but giving the weather in finnish:

```
.give Bane wunderground
```

Result:

```
supybot Uncaught exception in ['echo'].
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/supybot/callbacks.py", line 1267, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/supybot/callbacks.py", line 1248, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/supybot/commands.py", line 1071, in newf
    state = spec(irc, msg, args, stateAttrs={'cb': self, 'log': self.log})
  File "/usr/lib/python2.7/site-packages/supybot/commands.py", line 1057, in __call__
    context(irc, msg, args, state)
  File "/usr/lib/python2.7/site-packages/supybot/commands.py", line 837, in __call__
    self.converter(irc, msg, args, state, *self.args)
  File "/usr/lib/python2.7/site-packages/supybot/commands.py", line 715, in getText
    state.args.append(' '.join(args))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 67: ordinal not in range(128)
```

'args' with '.give Bane wunderground':

``` Python
[u'Bane,', '\x02Salo, Suomi\x02 :: Ukkosta :: \x030825C\x03 | \x02Maanantai\x02: Osittain pilvist\xc3\xa4. Ylin l\xc3\xa4mp\xc3\xb6tila 27\xc2\xbaC. Tuuli ESE, nopeus 15\xe2\x88\x9230 km/h. \x02Maanantaiy\xc3\xb6\x02: Aluksi ukkosta. Alin l\xc3\xa4mp\xc3\xb6tila 10\xc2\xbaC. Tuuli SSW, nopeus 15\xe2\x88\x9225 km/h. Sateen mahd: 50%.']
```

'echo [wunderground]' works fine, here's 'args' list with it:

``` Python
['\x02Salo, Suomi\x02 :: Ukkosta :: \x030825C\x03 | \x02Maanantai\x02: Osittain pilvist\xc3\xa4. Ylin l\xc3\xa4mp\xc3\xb6tila 27\xc2\xbaC. Tuuli ESE, nopeus 15\xe2\x88\x9230 km/h. \x02Maanantaiy\xc3\xb6\x02: Aluksi ukkosta. Alin l\xc3\xa4mp\xc3\xb6tila 10\xc2\xbaC. Tuuli SSW, nopeus 15\xe2\x88\x9225 km/h. Sateen mahd: 50%.']
```

**Comment by jlu5** [comment]
Closing, as Limnoria now requires Python 3.
