### ISSUE TITLE
Unicode and raw chars break re

### ISSUE THREAD

**Issue by OvermindDL1** [ProgVal/Limnoria#824]
Using Python 2.7.6, re is bugged:

```
<Me> ?re "s/e/e/" "ä"
<Bot> Me: (re <regexp> <text>) -- If <regexp> is of the form m/regexp/flags, returns the portion of <text> that matches the regexp. If <regexp> is of the form s/regexp/replacement/flags, returns the result of applying such a regexp to <text>.
```

```
<Me> ?re "s/./\1\1/" "ä"
<Bot> Me: (re <regexp> <text>) -- If <regexp> is of the form m/regexp/flags, returns the portion of <text> that matches the regexp. If <regexp> is of the form s/regexp/replacement/flags, returns the result of applying such a regexp to <text>.
```

```
<Me> ?re "s/./\1\1/" "a"
<Me> ?re "s/./\\1\\1/" "a"
<Me> ?re "s/./\\\1\\\1/" "a"
<Me> ?re "s/./\\\\1\\\\1/" "a"
All of those above output:
<Bot> Me: An error has occurred and has been logged. Check the logs for more informations.
```

The log contains:

```
ERROR 2014-08-25T04:17:14 Uncaught exception in ['re'].
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/supybot/callbacks.py", line 1268, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/callbacks.py", line 1249, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/commands.py", line 69, in newf
    f(self, irc, msg, args, *L, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/commands.py", line 1079, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/plugins/String/plugin.py", line 204, in re
    v = process(f, text, timeout=t, pn=self.name(), cn='re')
  File "/usr/local/lib/python2.7/dist-packages/supybot/commands.py", line 133, in process
    raise v
error: invalid group reference
ERROR 2014-08-25T04:17:14 Exception id: 0x7c58d
```

In general, re appears to be a bit broken...
This is using the latest version as of the time of this submit.

As far as I have diagnosed thus far with the reference (\1), it seems that "\1" becomes a literal [1], where "\1" becomes a literal ['\', '\', '1'] in the strings.

**Comment by jlu5** [comment]
Closing, as Limnoria now requires Python 3.
